### ISSUE TITLE
[Bug]: Conflict with Manager when switching new blank workflows using shortcuts

### ISSUE THREAD

**Issue by LukeG89** [Comfy-Org/ComfyUI_frontend#1130]
### Frontend Version

1.3.9

### Expected Behavior

No conflicts when switching new blank workflows created with the "+" button.

### Actual Behavior

When you switch new blank workflow tabs using shortcuts, there is a conflict when you try to reach the latest workflow and when you try to switch from the first one to the last one.

This is a really specific issue because with default and template workflows doesn't happen, neither if you create new blank workflows through the shortcut.
It only happens with the "+" button in Workflows tab.

![plus_button](https://github.com/user-attachments/assets/19f7abf2-880c-4739-a0ce-b3d559d18593)

In the conflict you can see rgthree mentioned, but if I disable it the problem remains.
If I keep rgthree enabled and disable only the Manager, the problem is gone.

### Steps to Reproduce

- Create some workflows with the "+" button in Workflows tab
- Switch workflow tabs using shortcuts

https://github.com/user-attachments/assets/e2b0186c-382f-47d3-b3a5-6b25a60cbe46

### Debug Logs

```powershell
No errors.
```

### Browser Logs

components-manager.js:740 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'extra')
    at app.loadGraphData (components-manager.js:740:29)
    at app.loadGraphData (rgthree.js:573:51)
    at Proxy.load (workflows.ts:243:30)
    at loadOpenedWorkflowIndexShift (workflowStore.ts:52:28)
    at Proxy.loadNextOpenedWorkflow (workflowStore.ts:58:11)
    at Proxy.wrappedAction (pinia.mjs:1405:26)
    at function (commandStore.ts:306:28)
    at errorHooks.ts:34:22
    at Proxy.execute (commandStore.ts:332:70)
    at Proxy.wrappedAction (pinia.mjs:1405:26)

### What browsers do you use to access the UI ?

Google Chrome

**Comment by LukeG89** [comment]
Update: It happens both creating with the "+" button and with shortcut. The shortcut one specifically when you try to switch from an existing workflow to the new blank one.

**Comment by LukeG89** [comment]
This bug seems fixed!
