### ISSUE TITLE
[Bug]: `Load Image` node doesn't show files in subfolders under `input`

### ISSUE THREAD

**Issue by Lex-DRL** [Comfy-Org/ComfyUI_frontend#1250]
### Frontend Version

v1.3.11

### Expected Behavior

The entire hierarchy of image files under `input` dir should be shown and available for selection.

### Actual Behavior

Only files in the root of `input` folder are displayed.

### Steps to Reproduce

* Create a subfolder under `input` folder.
* Put an image file there.
* Add a `Load Image` node in ComfyUI.
* Try selecting the image.

### Debug Logs

```powershell
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-10-13 18:24:45.991383
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: E:\SD\SwarmUI\dlbackend\ComfyUI\venv\Scripts\python.exe
** ComfyUI Path: E:\SD\SwarmUI\dlbackend\ComfyUI
** Log path: E:\SD\SwarmUI\dlbackend\ComfyUI\comfyui.log
[MaraScott] Initialization

Prestartup times for custom nodes:
   0.0 seconds: E:\SD\SwarmUI\dlbackend\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: E:\SD\SwarmUI\dlbackend\ComfyUI\custom_nodes\ComfyUI_MaraScott_Nodes
   2.8 seconds: E:\SD\SwarmUI\dlbackend\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24564 MB, total RAM 32549 MB
pytorch version: 2.4.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: E:\SD\SwarmUI\dlbackend\ComfyUI\web
E:\SD\SwarmUI\dlbackend\ComfyUI\venv\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
### Loading: ComfyUI-Impact-Pack (V7.10)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.7)
[Impact Pack] Wildcards loading done.
E:\SD\SwarmUI\dlbackend\ComfyUI\venv\Lib\site-packages\albumentations\__init__.py:13: UserWarning: A new version of Albumentations is available: 1.4.18 (you have 1.4.15). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
  check_for_updates()
Total VRAM 24564 MB, total RAM 32549 MB
pytorch version: 2.4.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
### Loading: ComfyUI-Manager (V2.51.7)
### ComfyUI Revision: 2759 [65aec4ac] | Released on '2024-10-13'
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
[comfyui_controlnet_aux] | INFO -> Using ckpts path: E:\SD\SwarmUI\dlbackend\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[MaraScott] Loaded
[comfy_mtb] | INFO -> loaded 83 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (5) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!

[rgthree-comfy] Loaded 42 fantastic nodes. 🎉


Import times for custom nodes:
   0.0 seconds: E:\SD\SwarmUI\dlbackend\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: E:\SD\SwarmUI\dlbackend\ComfyUI\custom_nodes\SD-Latent-Upscaler
   0.0 seconds: E:\SD\SwarmUI\dlbackend\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: E:\SD\SwarmUI\dlbackend\ComfyUI\custom_nodes\ComfyUI_ImageProcessing
   0.0 seconds: E:\SD\SwarmUI\dlbackend\ComfyUI\custom_nodes\ComfyUi_NNLatentUpscale
   0.0 seconds: E:\SD\SwarmUI\dlbackend\ComfyUI\custom_nodes\ComfyUI_JPS-Nodes
   0.0 seconds: E:\SD\SwarmUI\dlbackend\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: E:\SD\SwarmUI\dlbackend\ComfyUI\custom_nodes\comfyui-inpaint-nodes
   0.0 seconds: E:\SD\SwarmUI\dlbackend\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: E:\SD\SwarmUI\dlbackend\ComfyUI\custom_nodes\comfy-image-saver
   0.0 seconds: E:\SD\SwarmUI\dlbackend\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: E:\SD\SwarmUI\dlbackend\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: E:\SD\SwarmUI\dlbackend\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: E:\SD\SwarmUI\dlbackend\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: E:\SD\SwarmUI\dlbackend\ComfyUI\custom_nodes\ComfyUI-Static-Primitives
   0.0 seconds: E:\SD\SwarmUI\dlbackend\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.0 seconds: E:\SD\SwarmUI\dlbackend\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: E:\SD\SwarmUI\dlbackend\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: E:\SD\SwarmUI\dlbackend\ComfyUI\custom_nodes\ComfyUI_smZNodes
   0.1 seconds: E:\SD\SwarmUI\dlbackend\ComfyUI\custom_nodes\ComfyUI_MaraScott_Nodes
   0.1 seconds: E:\SD\SwarmUI\dlbackend\ComfyUI\custom_nodes\ComfyUI-HQ-Image-Save
   0.1 seconds: E:\SD\SwarmUI\dlbackend\ComfyUI\custom_nodes\ComfyUI-SAM2
   0.3 seconds: E:\SD\SwarmUI\dlbackend\ComfyUI\custom_nodes\ComfyUI-Manager
   0.3 seconds: E:\SD\SwarmUI\dlbackend\ComfyUI\custom_nodes\ComfyUI-layerdiffuse
   0.5 seconds: E:\SD\SwarmUI\dlbackend\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   1.0 seconds: E:\SD\SwarmUI\dlbackend\ComfyUI\custom_nodes\ComfyUI_LayerStyle
   1.1 seconds: E:\SD\SwarmUI\dlbackend\ComfyUI\custom_nodes\comfy_mtb
   1.6 seconds: E:\SD\SwarmUI\dlbackend\ComfyUI\custom_nodes\ComfyUI-Inspyrenet-Rembg

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: E:\SD\SwarmUI\dlbackend\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
```

### Browser Logs

Failed to get subsystem status for purpose 
Object { rejected: true, message: "UNSUPPORTED_OS" }
content-script.js:104:25
Running on 127.0.0.1:8188 api.ts:48:12
ComfyUI Front-end version: 1.3.11 logging.ts:332:13
Загрузка модуля по адресу «http://127.0.0.1:8188/extensions/dzNodes/dz_DZ_widgets.js» была заблокирована из-за неразрешенного MIME-типа («application/octet-stream»). 127.0.0.1:8188
Загрузка модуля по адресу «http://127.0.0.1:8188/extensions/dzNodes/dz_DZ_widgets.js» не удалась. 127.0.0.1:8188
Error loading extension /extensions/dzNodes/dz_debug.js TypeError: error loading dynamically imported module: http://127.0.0.1:8188/extensions/dzNodes/dz_debug.js app.ts:1729:20
Extension pysssss.Locking is disabled. extensionStore.ts:43:14
[mtb] - Aborting the loading of mtb's imageFeed in favor of pysssss.ImageFeed imageFeed.js:87:15
Error calling extension 'DZ.widgets' method 'init' 
Object { error: ReferenceError }
 
Object { extension: {…} }
 
Object { args: [] }
app.ts:407:20
Skipping invalid node definition: schedulerStaticCollectionPrimitive. See debug log for more information. api.ts:284:18
Invalid ComfyNodeDef: {"input":{"required":{"Input_scheduler":[["normal","karras","exponential","sgm_uniform","simple","ddim_uniform"]]}},"input_order":{"required":["Input_scheduler"]},"output":[["normal","karras","exponential","sgm_uniform","simple","ddim_uniform"]],"output_is_list":[false],"output_name":[["normal","karras","exponential","sgm_uniform","simple","ddim_uniform"]],"name":"schedulerStaticCollectionPrimitive","display_name":"Collection Primitive (scheduler)","description":"","python_module":"custom_nodes.ComfyUI-Static-Primitives","category":"primitives","output_node":false}
Validation error: Expected string, received array at "output_name[0]" api.ts:287:18
Skipping invalid node definition: samplerStaticCollectionPrimitive. See debug log for more information. api.ts:284:18
Invalid ComfyNodeDef: {"input":{"required":{"Input_sampler":[["euler","euler_ancestral","heun","heunpp2","dpm_2","dpm_2_ancestral","lms","dpm_fast","dpm_adaptive","dpmpp_2s_ancestral","dpmpp_sde","dpmpp_sde_gpu","dpmpp_2m","dpmpp_2m_sde","dpmpp_2m_sde_gpu","dpmpp_3m_sde","dpmpp_3m_sde_gpu","ddpm","lcm","ddim","uni_pc","uni_pc_bh2"]]}},"input_order":{"required":["Input_sampler"]},"output":[["euler","euler_ancestral","heun","heunpp2","dpm_2","dpm_2_ancestral","lms","dpm_fast","dpm_adaptive","dpmpp_2s_ancestral","dpmpp_sde","dpmpp_sde_gpu","dpmpp_2m","dpmpp_2m_sde","dpmpp_2m_sde_gpu","dpmpp_3m_sde","dpmpp_3m_sde_gpu","ddpm","lcm","ddim","uni_pc","uni_pc_bh2"]],"output_is_list":[false],"output_name":[["euler","euler_ancestral","heun","heunpp2","dpm_2","dpm_2_ancestral","lms","dpm_fast","dpm_adaptive","dpmpp_2s_ancestral","dpmpp_sde","dpmpp_sde_gpu","dpmpp_2m","dpmpp_2m_sde","dpmpp_2m_sde_gpu","dpmpp_3m_sde","dpmpp_3m_sde_gpu","ddpm","lcm","ddim","uni_pc","uni_pc_bh2"]],"name":"samplerStaticCollectionPrimitive","display_name":"Collection Primitive (sampler)","description":"","python_module":"custom_nodes.ComfyUI-Static-Primitives","category":"primitives","output_node":false}
Validation error: Expected string, received array at "output_name[0]" api.ts:287:18
Skipping invalid node definition: Scribble_PiDiNet_Preprocessor. See debug log for more information. api.ts:284:18
Invalid ComfyNodeDef: {"input":{"required":{"image":["IMAGE"]},"optional":{"safe":["enable","disable"],"resolution":["INT",{"default":512,"min":64,"max":16384,"step":64}]}},"input_order":{"required":["image"],"optional":["safe","resolution"]},"output":["IMAGE"],"output_is_list":[false],"output_name":["IMAGE"],"name":"Scribble_PiDiNet_Preprocessor","display_name":"Scribble PiDiNet Lines","description":"","python_module":"custom_nodes.comfyui_controlnet_aux","category":"ControlNet Preprocessors/Line Extractors","output_node":false}
Validation error: Array must contain at most 1 element(s) at "input.optional.safe" api.ts:287:18
Empty components: policy ignored components-manager.js:769:11
[🐍 pysssss] Skipping LinkRenderMode as core extension found linkRenderMode.js:9:12
Загрузка <script> по адресу «http://127.0.0.1:8188/extensions/ComfyUI_smZNodes/js/exif.js» не удалась. 127.0.0.1:8188:1:1
75 is def invalid; BOTH origin node 30 doesn't have 75 and 30 target node doesn't have 75. link_fixer.js:240:24
74 is def invalid; BOTH origin node 30 doesn't have 74 and 30 target node doesn't have 74. link_fixer.js:240:24
73 is def invalid; BOTH origin node 30 doesn't have 73 and 30 target node doesn't have 73. link_fixer.js:240:24
72 is def invalid; BOTH origin node 30 doesn't have 72 and 30 target node doesn't have 72. link_fixer.js:240:24
Would make no node link patches, and 4 stale link removals. link_fixer.js:275:16
[rgthree] The workflow you've loaded has corrupt linking data. Open http://127.0.0.1:8188/rgthree/link_fixer to try to fix. rgthree.js:522:79

### What browsers do you use to access the UI ?

Mozilla Firefox

**Comment by LukeG89** [comment]
This is not a bug but a "normal" behavior they've never solved in ComfyUI (I don't know why).

Two ways to access images in subfolders are:

- [comfyui-imagesubfolders](https://github.com/catscandrive/comfyui-imagesubfolders)
- `Load Image with metadata` from [ComfyUI-Crystools](https://github.com/crystian/ComfyUI-Crystools)

**Comment by Lex-DRL** [comment]
It's odd it's considered a normal behavior.
But thanks for  the workaround 👍🏻

Should I close the issue then? To me, it seems it's still valid.

**Comment by LukeG89** [comment]
Yes, keep it open. Let's wait for @huchenlei

**Comment by christian-byrne** [comment]
The file indexing is done on the backend.

In the ComfyUI code, there seems to be an attempt to not expose path-traversal to functions which accept user input, leaving such functionality to opt-in custom nodes/extensions. This is a good thing for a server to do.
