### ISSUE TITLE
[Bug]: RMB stopped working as of 1.3.20

### ISSUE THREAD

**Issue by shhlife** [Comfy-Org/ComfyUI_frontend#1286]
### Frontend Version

1.3.20

### Expected Behavior

RMB opens a right mouse button menu

### Actual Behavior

No menu appears, and I'm getting the following error:

```
TypeError: Class constructor InvertContextMenu cannot be invoked without 'new'
    at LiteGraph.ContextMenu (contextMenuHook.js:86:12)
    at new LiteGraph.ContextMenu (menu_auto_nest.js:36:44)
    at Proxy.processContextMenu (litegraph.es.js:9350:5)
    at Proxy.processMouseDown (litegraph.es.js:4806:14)
    at LGraphCanvas.processMouseDown (changeTracker.ts:203:34)
    at LGraphCanvas.processMouseDown (simpleTouchSupport.ts:103:27)
    at LGraphCanvas.processMouseDown (rgthree.js:247:48)
    at LGraphCanvas.processMouseDown (app.ts:1209:40)
    ```

### Steps to Reproduce

Make sure to run with the latest version..

`python main.py --front-end-version Comfy-Org/ComfyUI_frontend@1.3.20`

### Debug Logs

```powershell
PS C:\Users\jason\Documents\GitHub\ComfyUI> poetry run python main.py --front-end-version Comfy-Org/ComfyUI_frontend@1.3.20
[START] Security scan
WARNING: Ignoring invalid distribution ~riptape (C:\Users\jason\Documents\GitHub\ComfyUI\.venv\Lib\site-packages)
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-10-24 13:03:23.344723
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: C:\Users\jason\Documents\GitHub\ComfyUI\.venv\Scripts\python.exe
** ComfyUI Path: C:\Users\jason\Documents\GitHub\ComfyUI
** Log path: C:\Users\jason\Documents\GitHub\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: C:\Users\jason\Documents\GitHub\ComfyUI\custom_nodes\rgthree-comfy
   0.9 seconds: C:\Users\jason\Documents\GitHub\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 16376 MB, total RAM 32508 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 Laptop GPU : cudaMallocAsync
Using pytorch cross attention
Initializing frontend: Comfy-Org/ComfyUI_frontend@1.3.20, requesting version details from GitHub...
[Prompt Server] web root: C:\Users\jason\Documents\GitHub\ComfyUI\web_custom_versions\Comfy-Org_ComfyUI_frontend\1.3.20

[Griptape Custom Nodes]:
   - Custom routes initialized.
   - Loading configuration
   - Done!

### Loading: ComfyUI-Inspire-Pack (V0.81)
### Loading: ComfyUI-Manager (V2.46.3)
### ComfyUI Revision: 2783 [66b0961a] | Released on '2024-10-23'

[rgthree] Loaded 39 exciting nodes.


Import times for custom nodes:
   0.0 seconds: C:\Users\jason\Documents\GitHub\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: C:\Users\jason\Documents\GitHub\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: C:\Users\jason\Documents\GitHub\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: C:\Users\jason\Documents\GitHub\ComfyUI\custom_nodes\rgthree-comfy
   0.1 seconds: C:\Users\jason\Documents\GitHub\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.3 seconds: C:\Users\jason\Documents\GitHub\ComfyUI\custom_nodes\ComfyUI-Manager
   1.1 seconds: C:\Users\jason\Documents\GitHub\ComfyUI\custom_nodes\ComfyUI-Griptape

Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
```
```


### Browser Logs

```
TypeError: Class constructor InvertContextMenu cannot be invoked without 'new'
    at LiteGraph.ContextMenu (contextMenuHook.js:86:12)
    at new LiteGraph.ContextMenu (menu_auto_nest.js:36:44)
    at Proxy.processContextMenu (litegraph.es.js:9350:5)
    at Proxy.processMouseDown (litegraph.es.js:4806:14)
    at LGraphCanvas.processMouseDown (changeTracker.ts:203:34)
    at LGraphCanvas.processMouseDown (simpleTouchSupport.ts:103:27)
    at LGraphCanvas.processMouseDown (rgthree.js:247:48)
    at LGraphCanvas.processMouseDown (app.ts:1209:40)
    ```

### What browsers do you use to access the UI ?

Other

### Other

It's working in 1.3.19

**Comment by UrzasLegacy** [comment]
Same issue when trying to expand a dropdown menu

**Comment by huchenlei** [comment]
Culprit reverted.

**Comment by huchenlei** [comment]
Seems like there are extensions that depend on the fact that LiteGraph.ContextMenu being a function style constructor instead of an ES6 class. We need to fix these extension usages before relanding ts-strict PRs.
