### ISSUE TITLE
Enabling previews breaks audio node widgets

### ISSUE THREAD

**Issue by christian-byrne** [Comfy-Org/ComfyUI_frontend#141]
![Selection_051](https://github.com/user-attachments/assets/40dd2ac3-7bbb-40d0-b47c-633c0fd5739f)

Audio nodes are trying to get previews:

https://github.com/Comfy-Org/ComfyUI_frontend/blob/edb1349bb5183e5664597d66b358a962168ad5bc/src/extensions/core/uploadAudio.ts#L20-L34

Previews don't seem to be implemented for audio yet.

Terminal output:

```
Traceback (most recent call last):
  File "/home/c_byrne/projects/comfy-testing-environment/venv/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/c_byrne/projects/comfy-testing-environment/venv/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/c_byrne/projects/comfy-testing-environment/venv/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/c_byrne/projects/comfy-testing-environment/ComfyUI/server.py", line 43, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/c_byrne/projects/comfy-testing-environment/ComfyUI/server.py", line 296, in view_image
    with Image.open(file) as img:
         ^^^^^^^^^^^^^^^^
  File "/home/c_byrne/projects/comfy-testing-environment/venv/lib/python3.11/site-packages/PIL/Image.py", line 3339, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '/home/c_byrne/projects/comfy-testing-environment/ComfyUI/temp/ComfyUI_temp_tafpy_00002_.flac'
```

**Comment by christian-byrne** [comment]
Was fixed by [comfyanonymous/ComfyUI#4044](https://github.com/comfyanonymous/ComfyUI/pull/4044)
