### ISSUE TITLE
[Bug]: Unsaved Workflow can be easily overwritten

### ISSUE THREAD

**Issue by LukeG89** [Comfy-Org/ComfyUI_frontend#1415]
### Frontend Version

1.3.31

### Expected Behavior

When you create a new Unsaved Workflow, it cannot be overwritten by a new one.

### Actual Behavior

Unsaved Workflow can be easily overwritten.

### Steps to Reproduce

- Create a new Unsaved Workflow (blank or default)
- Make some changes
- Refresh the page o restart ComfyUI without saving
- The workflow is still here (with all the changes you made)
- Create a new blank or default workflow
- The previous Unsaved Workflow is overwritten and cannot be restored

https://github.com/user-attachments/assets/46323212-cbae-4124-8d5d-e7c6838afc4a

### Debug Logs

```powershell
E:\>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --disable-all-custom-nodes --preview-size 1024 --front-end-version Comfy-Org/ComfyUI_frontend@latest
Total VRAM 8192 MB, total RAM 65277 MB
pytorch version: 2.6.0.dev20241101+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Ti Laptop GPU : cudaMallocAsync
Using pytorch cross attention
Initializing frontend: Comfy-Org/ComfyUI_frontend@latest, requesting version details from GitHub...
[Prompt Server] web root: E:\ComfyUI\web_custom_versions\Comfy-Org_ComfyUI_frontend\1.3.31
E:\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
Skipping loading of custom nodes
Starting server

To see the GUI go to: http://127.0.0.1:8188
```

### Browser Logs

```
Running on 127.0.0.1:8188
logging.ts:333 ComfyUI Front-end version: 1.3.31
index.mjs:101 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'style')
    at Proxy.updateInkBar (index.mjs:101:16)
    at Proxy.<anonymous> (index.mjs:48:13)
```

### Setting JSON

[comfy.settings.json](https://github.com/user-attachments/files/17611542/comfy.settings.json)

### What browsers do you use to access the UI ?

Google Chrome

**Comment by LukeG89** [comment]
This issue is fixed!
