### ISSUE TITLE
[Bug]: The sidebar [queue] display preview feature suddenly loses all preview images during prolonged use

### ISSUE THREAD

**Issue by Tanglinling** [Comfy-Org/ComfyUI_frontend#1426]
### Frontend Version

![image](https://github.com/user-attachments/assets/3fd1384e-8788-4016-8170-c49a088fd939)

### Expected Behavior

The sidebar Queue displays the preview

### Actual Behavior

The sidebar [queue] display preview feature suddenly loses all preview images during prolonged use
![image](https://github.com/user-attachments/assets/99e1f9e4-3f62-4293-bbca-20381d6c35ce)

### Steps to Reproduce

![workflow (1)](https://github.com/user-attachments/assets/7649dbc5-3a80-40e7-ae60-d3ab0c2a3a2f)

### Debug Logs

```powershell
2024-11-04 20:13:51,030 - root - INFO - Total VRAM 8188 MB, total RAM 32476 MB
2024-11-04 20:13:51,030 - root - INFO - pytorch version: 2.4.0+cu121
2024-11-04 20:13:52,322 - root - INFO - xformers version: 0.0.27.post2
2024-11-04 20:13:52,322 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-04 20:13:52,322 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4060 Laptop GPU : cudaMallocAsync
2024-11-04 20:13:52,651 - root - INFO - Using xformers cross attention
2024-11-04 20:13:53,766 - root - INFO - [Prompt Server] web root: D:\ComfyUI\web
2024-11-04 20:13:59,242 - root - INFO - Total VRAM 8188 MB, total RAM 32476 MB
2024-11-04 20:13:59,243 - root - INFO - pytorch version: 2.4.0+cu121
2024-11-04 20:13:59,243 - root - INFO - xformers version: 0.0.27.post2
2024-11-04 20:13:59,244 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-04 20:13:59,244 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4060 Laptop GPU : cudaMallocAsync
2024-11-04 20:14:03,705 - root - INFO - --------------
2024-11-04 20:14:03,706 - root - INFO - [91m ### Mixlab Nodes: [93mLoaded
2024-11-04 20:14:03,736 - root - INFO - ChatGPT.available True
2024-11-04 20:14:03,738 - root - INFO - edit_mask.available True
2024-11-04 20:14:05,909 - root - INFO - ClipInterrogator.available True
2024-11-04 20:14:06,474 - root - INFO - PromptGenerate.available True
2024-11-04 20:14:06,474 - root - INFO - ChinesePrompt.available True
2024-11-04 20:14:06,475 - root - INFO - RembgNode_.available True
2024-11-04 20:14:07,902 - root - INFO - TripoSR.available
2024-11-04 20:14:07,904 - root - INFO - MiniCPMNode.available
2024-11-04 20:14:08,292 - root - INFO - Scenedetect.available
2024-11-04 20:14:08,550 - root - INFO - FishSpeech.available
2024-11-04 20:14:08,587 - root - INFO - SenseVoice.available
2024-11-04 20:14:09,235 - root - INFO - Whisper.available False
2024-11-04 20:14:09,267 - root - INFO - FalVideo.available
2024-11-04 20:14:09,267 - root - INFO - [93m -------------- [0m
2024-11-04 20:14:15,495 - root - INFO - 
Import times for custom nodes:
2024-11-04 20:14:15,495 - root - INFO -    0.0 seconds: D:\ComfyUI\custom_nodes\AIGODLIKE-COMFYUI-TRANSLATION
2024-11-04 20:14:15,496 - root - INFO -    0.0 seconds: D:\ComfyUI\custom_nodes\websocket_image_save.py
2024-11-04 20:14:15,496 - root - INFO -    0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Inpaint-CropAndStitch
2024-11-04 20:14:15,496 - root - INFO -    0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI-SDXL-Style-Preview
2024-11-04 20:14:15,497 - root - INFO -    0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI_densediffusion
2024-11-04 20:14:15,497 - root - INFO -    0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI_3dPoseEditor
2024-11-04 20:14:15,497 - root - INFO -    0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI-TiledDiffusion
2024-11-04 20:14:15,498 - root - INFO -    0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2024-11-04 20:14:15,498 - root - INFO -    0.0 seconds: D:\ComfyUI\custom_nodes\MistoControlNet-Flux-dev
2024-11-04 20:14:15,498 - root - INFO -    0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
2024-11-04 20:14:15,498 - root - INFO -    0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI_FizzNodes
2024-11-04 20:14:15,499 - root - INFO -    0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI_essentials
2024-11-04 20:14:15,499 - root - INFO -    0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI-layerdiffuse
2024-11-04 20:14:15,499 - root - INFO -    0.0 seconds: D:\ComfyUI\custom_nodes\Comfyui_CXH_joy_caption
2024-11-04 20:14:15,499 - root - INFO -    0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Fluxtapoz
2024-11-04 20:14:15,499 - root - INFO -    0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2024-11-04 20:14:15,499 - root - INFO -    0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
2024-11-04 20:14:15,499 - root - INFO -    0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI-MimicMotionWrapper
2024-11-04 20:14:15,501 - root - INFO -    0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
2024-11-04 20:14:15,501 - root - INFO -    0.1 seconds: D:\ComfyUI\custom_nodes\ComfyUI-GGUF
2024-11-04 20:14:15,501 - root - INFO -    0.1 seconds: D:\ComfyUI\custom_nodes\ComfyUI-IC-Light
2024-11-04 20:14:15,501 - root - INFO -    0.1 seconds: D:\ComfyUI\custom_nodes\ComfyUI-KJNodes
2024-11-04 20:14:15,501 - root - INFO -    0.1 seconds: D:\ComfyUI\custom_nodes\efficiency-nodes-comfyui
2024-11-04 20:14:15,502 - root - INFO -    0.1 seconds: D:\ComfyUI\custom_nodes\rgthree-comfy
2024-11-04 20:14:15,502 - root - INFO -    0.1 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Kolors-MZ
2024-11-04 20:14:15,502 - root - INFO -    0.1 seconds: D:\ComfyUI\custom_nodes\ComfyUI-LivePortraitKJ
2024-11-04 20:14:15,502 - root - INFO -    0.1 seconds: D:\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-11-04 20:14:15,502 - root - INFO -    0.1 seconds: D:\ComfyUI\custom_nodes\comfyui-workspace-manager
2024-11-04 20:14:15,503 - root - INFO -    0.1 seconds: D:\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-11-04 20:14:15,503 - root - INFO -    0.1 seconds: D:\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
2024-11-04 20:14:15,503 - root - INFO -    0.1 seconds: D:\ComfyUI\custom_nodes\ComfyUI-MingNodes
2024-11-04 20:14:15,503 - root - INFO -    0.2 seconds: D:\ComfyUI\custom_nodes\ComfyUI-KwaiKolorsWrapper
2024-11-04 20:14:15,503 - root - INFO -    0.2 seconds: D:\ComfyUI\custom_nodes\ComfyUI-DynamiCrafterWrapper
2024-11-04 20:14:15,504 - root - INFO -    0.2 seconds: D:\ComfyUI\custom_nodes\PuLID_ComfyUI
2024-11-04 20:14:15,504 - root - INFO -    0.3 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
2024-11-04 20:14:15,504 - root - INFO -    0.4 seconds: D:\ComfyUI\custom_nodes\ComfyUI_LayerStyle
2024-11-04 20:14:15,504 - root - INFO -    0.5 seconds: D:\ComfyUI\custom_nodes\ComfyUI-segment-anything-2
2024-11-04 20:14:15,504 - root - INFO -    0.5 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Manager
2024-11-04 20:14:15,504 - root - INFO -    0.8 seconds: D:\ComfyUI\custom_nodes\ComfyUI_InstantID
2024-11-04 20:14:15,504 - root - INFO -    0.8 seconds: D:\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
2024-11-04 20:14:15,504 - root - INFO -    0.8 seconds: D:\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait
2024-11-04 20:14:15,504 - root - INFO -    0.9 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Easy-Use
2024-11-04 20:14:15,504 - root - INFO -    1.1 seconds: D:\ComfyUI\custom_nodes\ComfyUI-BrushNet
2024-11-04 20:14:15,504 - root - INFO -    1.3 seconds: D:\ComfyUI\custom_nodes\ComfyUI-SUPIR
2024-11-04 20:14:15,504 - root - INFO -    1.4 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Crystools
2024-11-04 20:14:15,504 - root - INFO -    1.7 seconds: D:\ComfyUI\custom_nodes\comfyui-reactor-node
2024-11-04 20:14:15,504 - root - INFO -    8.7 seconds: D:\ComfyUI\custom_nodes\comfyui-mixlab-nodes
2024-11-04 20:14:15,504 - root - INFO - 
2024-11-04 20:14:15,554 - root - INFO - Starting server

2024-11-04 20:14:15,554 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-11-04 20:14:30,709 - asyncio - ERROR - Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\Tang linlin\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Tang linlin\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
2024-11-04 20:50:33,526 - root - INFO - got prompt
2024-11-04 20:50:34,187 - root - ERROR - Failed to validate prompt for output 533:
2024-11-04 20:50:34,187 - root - ERROR - * easy fullkSampler 137:
2024-11-04 20:50:34,188 - root - ERROR -   - Required input is missing: pipe
2024-11-04 20:50:34,188 - root - ERROR - Output will be ignored
2024-11-04 20:50:34,188 - root - ERROR - Failed to validate prompt for output 137:
2024-11-04 20:50:34,189 - root - ERROR - * (prompt):
2024-11-04 20:50:34,189 - root - ERROR -   - Required input is missing: pipe
2024-11-04 20:50:34,189 - root - ERROR - Output will be ignored
2024-11-04 20:50:34,189 - root - ERROR - Failed to validate prompt for output 472:
2024-11-04 20:50:34,190 - root - ERROR - Output will be ignored
2024-11-04 20:50:34,276 - root - WARNING - WARNING: PlaySound.IS_CHANGED() missing 1 required positional argument: 'self'
2024-11-04 20:50:34,280 - root - WARNING - WARNING: PlaySound.IS_CHANGED() missing 1 required positional argument: 'self'
2024-11-04 20:50:34,885 - root - INFO - Using xformers attention in VAE
2024-11-04 20:50:34,885 - root - INFO - Using xformers attention in VAE
2024-11-04 20:50:37,162 - root - INFO - model weight dtype torch.float16, manual cast: None
2024-11-04 20:50:37,178 - root - INFO - model_type EPS
2024-11-04 20:50:50,139 - root - INFO - Using xformers attention in VAE
2024-11-04 20:50:50,144 - root - INFO - Using xformers attention in VAE
2024-11-04 20:50:51,327 - root - INFO - Requested to load SDXLClipModel
2024-11-04 20:50:51,328 - root - INFO - Loading 1 new model
2024-11-04 20:50:51,344 - root - INFO - loaded completely 0.0 1560.802734375 True
2024-11-04 20:50:54,825 - root - INFO - Requested to load SDXLClipModel
2024-11-04 20:50:54,826 - root - INFO - Loading 1 new model
2024-11-04 20:50:55,524 - root - INFO - Requested to load SDXLClipModel
2024-11-04 20:50:55,524 - root - INFO - Loading 1 new model
2024-11-04 20:50:57,453 - root - INFO - Requested to load SDXL
2024-11-04 20:50:57,454 - root - INFO - Loading 1 new model
2024-11-04 20:50:58,751 - root - INFO - loaded completely 0.0 4897.0483474731445 True
2024-11-04 20:51:25,121 - root - INFO - Requested to load SDXLClipModel
2024-11-04 20:51:25,123 - root - INFO - Loading 1 new model
2024-11-04 20:51:26,260 - root - INFO - loaded completely 0.0 1560.802734375 True
2024-11-04 20:51:26,290 - root - INFO - Unloading models for lowram load.
2024-11-04 20:51:26,331 - root - INFO - 0 models unloaded.
2024-11-04 20:53:22,334 - root - INFO - Prompt executed in 168.13 seconds
2024-11-04 20:54:31,527 - root - INFO - got prompt
2024-11-04 20:54:32,250 - root - ERROR - Failed to validate prompt for output 533:
2024-11-04 20:54:32,251 - root - ERROR - * easy fullkSampler 137:
2024-11-04 20:54:32,251 - root - ERROR -   - Required input is missing: pipe
2024-11-04 20:54:32,251 - root - ERROR - Output will be ignored
2024-11-04 20:54:32,252 - root - ERROR - Failed to validate prompt for output 137:
2024-11-04 20:54:32,252 - root - ERROR - * (prompt):
2024-11-04 20:54:32,252 - root - ERROR -   - Required input is missing: pipe
2024-11-04 20:54:32,252 - root - ERROR - Output will be ignored
2024-11-04 20:54:32,253 - root - ERROR - Failed to validate prompt for output 472:
2024-11-04 20:54:32,254 - root - ERROR - Output will be ignored
2024-11-04 20:54:32,293 - root - WARNING - WARNING: PlaySound.IS_CHANGED() missing 1 required positional argument: 'self'
2024-11-04 20:54:32,293 - root - WARNING - WARNING: PlaySound.IS_CHANGED() missing 1 required positional argument: 'self'
2024-11-04 20:55:47,649 - root - INFO - Prompt executed in 75.38 seconds
2024-11-04 20:57:23,129 - root - INFO - got prompt
2024-11-04 20:57:23,809 - root - ERROR - Failed to validate prompt for output 533:
2024-11-04 20:57:23,810 - root - ERROR - * easy fullkSampler 137:
2024-11-04 20:57:23,810 - root - ERROR -   - Required input is missing: pipe
2024-11-04 20:57:23,810 - root - ERROR - Output will be ignored
2024-11-04 20:57:23,811 - root - ERROR - Failed to validate prompt for output 137:
2024-11-04 20:57:23,811 - root - ERROR - * (prompt):
2024-11-04 20:57:23,812 - root - ERROR -   - Required input is missing: pipe
2024-11-04 20:57:23,813 - root - ERROR - Output will be ignored
2024-11-04 20:57:23,813 - root - ERROR - Failed to validate prompt for output 472:
2024-11-04 20:57:23,813 - root - ERROR - Output will be ignored
2024-11-04 20:57:23,843 - root - WARNING - WARNING: PlaySound.IS_CHANGED() missing 1 required positional argument: 'self'
2024-11-04 20:57:23,843 - root - WARNING - WARNING: PlaySound.IS_CHANGED() missing 1 required positional argument: 'self'
2024-11-04 20:59:12,476 - root - INFO - Prompt executed in 108.65 seconds
2024-11-04 21:15:02,502 - asyncio - ERROR - Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\Tang linlin\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Tang linlin\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
2024-11-04 21:15:02,506 - asyncio - ERROR - Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\Tang linlin\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Tang linlin\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
2024-11-04 22:00:35,888 - root - INFO - got prompt
2024-11-04 22:00:36,548 - root - ERROR - Failed to validate prompt for output 533:
2024-11-04 22:00:36,549 - root - ERROR - * easy fullkSampler 137:
2024-11-04 22:00:36,549 - root - ERROR -   - Required input is missing: pipe
2024-11-04 22:00:36,551 - root - ERROR - Output will be ignored
2024-11-04 22:00:36,552 - root - ERROR - Failed to validate prompt for output 137:
2024-11-04 22:00:36,552 - root - ERROR - * (prompt):
2024-11-04 22:00:36,553 - root - ERROR -   - Required input is missing: pipe
2024-11-04 22:00:36,553 - root - ERROR - Output will be ignored
2024-11-04 22:00:36,554 - root - ERROR - Failed to validate prompt for output 472:
2024-11-04 22:00:36,554 - root - ERROR - Output will be ignored
2024-11-04 22:00:36,625 - root - WARNING - WARNING: PlaySound.IS_CHANGED() missing 1 required positional argument: 'self'
2024-11-04 22:00:36,625 - root - WARNING - WARNING: PlaySound.IS_CHANGED() missing 1 required positional argument: 'self'
2024-11-04 22:00:37,748 - root - INFO - Prompt executed in 1.18 seconds
2024-11-04 22:00:40,672 - root - INFO - got prompt
2024-11-04 22:00:41,328 - root - ERROR - Failed to validate prompt for output 533:
2024-11-04 22:00:41,328 - root - ERROR - * easy fullkSampler 137:
2024-11-04 22:00:41,328 - root - ERROR -   - Required input is missing: pipe
2024-11-04 22:00:41,328 - root - ERROR - Output will be ignored
2024-11-04 22:00:41,328 - root - ERROR - Failed to validate prompt for output 137:
2024-11-04 22:00:41,328 - root - ERROR - * (prompt):
2024-11-04 22:00:41,328 - root - ERROR -   - Required input is missing: pipe
2024-11-04 22:00:41,328 - root - ERROR - Output will be ignored
2024-11-04 22:00:41,328 - root - ERROR - Failed to validate prompt for output 472:
2024-11-04 22:00:41,328 - root - ERROR - Output will be ignored
2024-11-04 22:00:41,377 - root - WARNING - WARNING: PlaySound.IS_CHANGED() missing 1 required positional argument: 'self'
2024-11-04 22:00:41,382 - root - WARNING - WARNING: PlaySound.IS_CHANGED() missing 1 required positional argument: 'self'
2024-11-04 22:01:55,453 - root - INFO - Prompt executed in 74.10 seconds
2024-11-04 22:03:05,239 - root - INFO - got prompt
2024-11-04 22:03:06,161 - root - INFO - model weight dtype torch.float16, manual cast: None
2024-11-04 22:03:06,161 - root - INFO - model_type EPS
2024-11-04 22:03:16,181 - root - INFO - Using xformers attention in VAE
2024-11-04 22:03:16,184 - root - INFO - Using xformers attention in VAE
2024-11-04 22:03:17,002 - root - INFO - Requested to load SDXLClipModel
2024-11-04 22:03:17,003 - root - INFO - Loading 1 new model
2024-11-04 22:03:17,015 - root - INFO - loaded completely 0.0 1560.802734375 True
2024-11-04 22:03:20,918 - root - INFO - Requested to load SDXL
2024-11-04 22:03:20,918 - root - INFO - Loading 1 new model
2024-11-04 22:03:23,100 - root - INFO - loaded completely 0.0 4897.0483474731445 True
2024-11-04 22:03:27,305 - root - INFO - Requested to load AutoencoderKL
2024-11-04 22:03:27,305 - root - INFO - Loading 1 new model
2024-11-04 22:03:27,742 - root - INFO - loaded completely 0.0 159.55708122253418 True
2024-11-04 22:03:27,976 - root - INFO - Prompt executed in 22.73 seconds
```

### Browser Logs

![image](https://github.com/user-attachments/assets/03b4eb84-352f-41d5-9efd-330052df2ac6)
![image](https://github.com/user-attachments/assets/919d7fad-a9e8-4ff4-9148-fb810175d670)
![image](https://github.com/user-attachments/assets/8da33e17-2e19-4329-be5d-5e796b848fa6)
![image](https://github.com/user-attachments/assets/18c29edd-5ddb-42bf-ab27-3d3b9d85f652)
![image](https://github.com/user-attachments/assets/92f4b00c-7516-4606-99d9-db56a8e3f6a5)

### Setting JSON

[comfy.settings.json](https://github.com/user-attachments/files/17619387/comfy.settings.json)

### What browsers do you use to access the UI ?

Google Chrome

**Comment by huchenlei** [comment]
Duplicated with https://github.com/Comfy-Org/ComfyUI_frontend/issues/1329. Fixed in https://github.com/Comfy-Org/ComfyUI_frontend/pull/1386 ([v1.3.30](https://github.com/Comfy-Org/ComfyUI_frontend/releases/tag/v1.3.30)). (Not yet reached main repo)
