### ISSUE TITLE
[Bug]: Manage Group Nodes button doesn't work.

### ISSUE THREAD

**Issue by comfyanonymous** [Comfy-Org/ComfyUI_frontend#1924]
### Frontend Version

1.5.18

### Expected Behavior

The menu opens.

### Actual Behavior

Nothing happens.

### Steps to Reproduce

Create a new group node.

Right click canvas -> Manage Group Nodes.

### Debug Logs

```powershell
not relevant
```

### Browser Logs

caught TypeError: Cannot read properties of undefined (reading 'nodeData')
    at ManageGroupDialog.getGroupData (￼:8188/assets/index-BNMdgttb.js:509:44)
    at ManageGroupDialog.changeGroup (￼:8188/assets/index-BNMdgttb.js:514:10)
    at ManageGroupDialog.show (￼:8188/assets/index-BNMdgttb.js:856:10)
    at HTMLDivElement.manageGroupNodes (￼:8188/assets/index-BNMdgttb.js:2035:30)
    at HTMLDivElement.inner_onclick (￼:8188/assets/index-CSl7lfOs.js:45257:38)

### Setting JSON

not relevant

**Comment by webfiltered** [comment]
Confirmed: 5c6eecd660275427d492742a6213aee70b5eadd9
