### ISSUE TITLE
[Bug]: Nested dynamic prompt causes error on queueing

### ISSUE THREAD

**Issue by Bluberius** [Comfy-Org/ComfyUI_frontend#2073]
### Frontend Version

ComfyUI v0.3.10-2-g160ca08
ComfyUI_frontend v1.5.19

### Expected Behavior

Queue button should start generation

### Actual Behavior

About one in two klicks on the Queue button does nothing. It's as if it wasn't pressed.

### Steps to Reproduce

Use the default generation template and paste this into the positive prompt: "
({forest | grass plain, { with river | with rocks | } | mountain}),
{people going for a walk | birds flying}
"
![ComfyUI_00001_](https://github.com/user-attachments/assets/a7009d83-32b0-47ed-9722-5e555b9011b8)

### Debug Logs

```powershell
X:\ComfyUI\CleanInstall\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Total VRAM 12282 MB, total RAM 64583 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 Ti : cudaMallocAsync
Using pytorch attention
[Prompt Server] web root: X:\ComfyUI\CleanInstall\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\web

Import times for custom nodes:
   0.0 seconds: X:\ComfyUI\CleanInstall\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py

Starting server

To see the GUI go to: http://127.0.0.1:8188
```

### Browser Logs

ComfyUI Front-end version: 1.5.19
:8188/favicon.ico:1 
        
        
        Failed to load resource: the server responded with a status of 404 (Not Found)
:8188/api/userdata?dir=workflows&recurse=true&split=false&full_info=true:1 
        
        
        Failed to load resource: the server responded with a status of 404 (Not Found)
:8188/api/prompt:1 
        
        
        Failed to load resource: the server responded with a status of 400 (Bad Request)
:8188/api/prompt:1 
        
        
        Failed to load resource: the server responded with a status of 400 (Bad Request)
2dynamicPrompts.ts:42  Uncaught (in promise) RangeError: Invalid string length
    at widget.serializeValue (dynamicPrompts.ts:42:15)
    at ComfyApp.graphToPrompt (app.ts:2400:32)
    at ComfyApp.queuePrompt (app.ts:2538:32)
    at function (coreCommandHooks.ts:285:13)
    at errorHooks.ts:41:22
    at Proxy.execute (commandStore.ts:93:70)
    at Proxy.wrappedAction (pinia.mjs:1405:26)
    at queuePrompt (ComfyQueueButton.vue:117:16)
    at callWithErrorHandling (runtime-core.esm-bundler.js:195:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:202:17)
:8188/api/prompt:1 
        
        
        Failed to load resource: the server responded with a status of 400 (Bad Request)
2dynamicPrompts.ts:42  Uncaught (in promise) RangeError: Invalid string length
    at widget.serializeValue (dynamicPrompts.ts:42:15)
    at ComfyApp.graphToPrompt (app.ts:2400:32)
    at ComfyApp.queuePrompt (app.ts:2538:32)
    at function (coreCommandHooks.ts:285:13)
    at errorHooks.ts:41:22
    at Proxy.execute (commandStore.ts:93:70)
    at Proxy.wrappedAction (pinia.mjs:1405:26)
    at queuePrompt (ComfyQueueButton.vue:117:16)
    at callWithErrorHandling (runtime-core.esm-bundler.js:195:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:202:17)
:8188/api/prompt:1 
        
        
        Failed to load resource: the server responded with a status of 400 (Bad Request)
:8188/api/prompt:1 
        
        
        Failed to load resource: the server responded with a status of 400 (Bad Request)
dynamicPrompts.ts:42  Uncaught (in promise) RangeError: Invalid string length
    at widget.serializeValue (dynamicPrompts.ts:42:15)
    at ComfyApp.graphToPrompt (app.ts:2400:32)
    at ComfyApp.queuePrompt (app.ts:2538:32)
    at function (coreCommandHooks.ts:285:13)
    at errorHooks.ts:41:22
    at Proxy.execute (commandStore.ts:93:70)
    at Proxy.wrappedAction (pinia.mjs:1405:26)
    at queuePrompt (ComfyQueueButton.vue:117:16)
    at callWithErrorHandling (runtime-core.esm-bundler.js:195:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:202:17)
api.ts:201 
        
        
POST http://127.0.0.1:8188/api/prompt 400 (Bad Request)
fetchApi @ api.ts:201
queuePrompt @ api.ts:463
queuePrompt @ app.ts:2542
await in queuePrompt
function @ coreCommandHooks.ts:285
(anonym) @ errorHooks.ts:41
execute @ commandStore.ts:93
wrappedAction @ pinia.mjs:1405
queuePrompt @ ComfyQueueButton.vue:117
callWithErrorHandling @ runtime-core.esm-bundler.js:195
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:202
emit @ runtime-core.esm-bundler.js:726
onDefaultButtonClick @ index.mjs:157
callWithErrorHandling @ runtime-core.esm-bundler.js:195
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:202
invoker @ runtime-dom.esm-bundler.js:693
dynamicPrompts.ts:42  Uncaught (in promise) RangeError: Invalid string length
    at widget.serializeValue (dynamicPrompts.ts:42:15)
    at ComfyApp.graphToPrompt (app.ts:2400:32)
    at ComfyApp.queuePrompt (app.ts:2538:32)
    at function (coreCommandHooks.ts:285:13)
    at errorHooks.ts:41:22
    at Proxy.execute (commandStore.ts:93:70)
    at Proxy.wrappedAction (pinia.mjs:1405:26)
    at queuePrompt (ComfyQueueButton.vue:117:16)
    at callWithErrorHandling (runtime-core.esm-bundler.js:195:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:202:17)

### Setting JSON

[comfy.settings.json](https://github.com/user-attachments/files/18260214/comfy.settings.json)

### What browsers do you use to access the UI ?

Mozilla Firefox, Microsoft Edge

### Other

About one in two klicks on the "Queue" button does nothing and generate an Error in the browser log. However the comfy server console doesn't show any error.
(please ignore the "Failed to load resource: the server responded with a status of 400 (Bad Request)
:8188/api/prompt:1 " Erorrs, those are when the button worked but I didn't have a model loaded in my attempt at a completely clean instance of comfy)

It seems to be an issue with the nested curly braces.
I've tried both Firefox and Edge.
I can reproduce this issue on a completely fresh install of ComfyUI.

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-2073-Bug-Nested-dynamic-prompt-causes-error-on-queueing-16e6d73d3650815aadb1c76733cb5103) by [Unito](https://www.unito.io)

**Comment by LukeG89** [comment]
Apparently you can't nest dynamic prompts inside dymanic prompts natively (I don't know if it was working before or it's a bug), but it's working with `ImpactWildcardProcessor` from [ComfyUI-Impact-Pack](https://github.com/ltdrdata/ComfyUI-Impact-Pack)
I would suggest using that node, you can have better control with it (e.g. you can see the resulting prompt, fixed seed keeps the prompt, etc.)


https://github.com/user-attachments/assets/035152d2-783c-427a-9d54-981ddc313c85
