### ISSUE TITLE
[Bug]: Workflow loading error

### ISSUE THREAD

**Issue by JackEllie** [Comfy-Org/ComfyUI_frontend#381]
### Frontend Version

1.2.17

### Expected Behavior

Reading workflow from PNG images
![I2I](https://github.com/user-attachments/assets/f1c65d3b-b73e-400e-b671-24e416ef9a5c)

### Actual Behavior

When I upgraded the version to 1.2.17, the error was as follows
```
Loading aborted due to error reloading workflow data

TypeError: Cannot redefine property: 0
TypeError: Cannot redefine property: 0
    at Function.defineProperty (<anonymous>)
    at lockArray (http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/locking.js:13:10)
    at lockNode (http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/locking.js:117:5)
    at nodeType.onConfigure (http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/locking.js:181:5)
    at nodeType.onConfigure (http://127.0.0.1:8188/extensions/ComfyUI-Easy-Use/js/easy/easyWidgets.js:377:57)
    at o.configure (http://127.0.0.1:8188/assets/index-B3RD2RYX.js:1127:21807)
    at er.configure (http://127.0.0.1:8188/assets/index-B3RD2RYX.js:1127:18379)
    at LGraph.configure (http://127.0.0.1:8188/assets/index-B3RD2RYX.js:1438:7864)
    at LGraph.configure (http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/snapToGrid.js:160:21)
    at LGraph.configure (http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/reroutePrimitive.js:14:29)
This may be due to the following script:
/extensions/ComfyUI-Custom-Scripts/js/locking.js
```
![螢幕擷取畫面 2024-08-12 182234](https://github.com/user-attachments/assets/d7359cce-64eb-4548-9dc3-3597cb2ec427)

### Steps to Reproduce

Use this image to read the workflow
![I2I](https://github.com/user-attachments/assets/1d6b3f8d-4dcf-484a-a1a8-d518b3ba015f)

### Debug Logs

```powershell
To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[comfy_mtb] | INFO -> Found multiple match, we will pick the last D:/Stable-diffusion/DAT
['C:\\ComfyUI_windows_portable\\ComfyUI\\models\\upscale_models', 'D:/Stable-diffusion/ESRGAN', 'D:/Stable-diffusion/RealESRGAN', 'D:/Stable-diffusion/SwinIR', 'D:/Stable-diffusion/DAT']
FETCH DATA from: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]

```
No error is displayed

### Browser Logs

![image](https://github.com/user-attachments/assets/2e5deeee-1d1d-4778-b853-a365cb58c1ce)

### What browsers do you use to access the UI ?

Google Chrome

### Other

Works fine on 1.2.16

**Comment by huchenlei** [comment]
Culprit reverted in https://github.com/Comfy-Org/ComfyUI_frontend/releases/tag/v1.2.18
