### ISSUE TITLE
[Bug]: infinitely loading nodes in the search engine

### ISSUE THREAD

**Issue by DonDanDojo** [Comfy-Org/ComfyUI_frontend#461]
### Frontend Version

1.2.25

### Expected Behavior

Load nodes from the search bar

### Actual Behavior

Can't load nodes 

![Zrzut ekranu 2024-08-16 140223](https://github.com/user-attachments/assets/26b520ed-d571-443e-b05c-abd402fa1a44)

### Steps to Reproduce

Launching recently updated comfyui throught Stability Matrix with --front-end-version Comfy-Org/ComfyUI_frontend@latest

### Debug Logs

```powershell
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-08-16 13:56:00.548797
** Platform: Windows
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
** Python executable: X:\SD Launcher\SD nowy\Packages\ComfyUI\venv\Scripts\python.exe
** ComfyUI Path: X:\SD Launcher\SD nowy\Packages\ComfyUI
** Log path: X:\SD Launcher\SD nowy\Packages\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\rgthree-comfy
   1.4 seconds: X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 12287 MB, total RAM 16328 MB
pytorch version: 2.1.2+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: X:\SD Launcher\SD nowy\Packages\ComfyUI\web_custom_versions\Comfy-Org_ComfyUI_frontend\1.2.25
Adding extra search path checkpoints X:\SD Launcher\SD nowy\Models\StableDiffusion
Adding extra search path vae X:\SD Launcher\SD nowy\Models\VAE
Adding extra search path loras X:\SD Launcher\SD nowy\Models\Lora
Adding extra search path loras X:\SD Launcher\SD nowy\Models\LyCORIS
Adding extra search path upscale_models X:\SD Launcher\SD nowy\Models\ESRGAN
Adding extra search path upscale_models X:\SD Launcher\SD nowy\Models\RealESRGAN
Adding extra search path upscale_models X:\SD Launcher\SD nowy\Models\SwinIR
Adding extra search path embeddings X:\SD Launcher\SD nowy\Models\TextualInversion
Adding extra search path hypernetworks X:\SD Launcher\SD nowy\Models\Hypernetwork
Adding extra search path controlnet X:\SD Launcher\SD nowy\Models\ControlNet
Adding extra search path controlnet X:\SD Launcher\SD nowy\Models\T2IAdapter
Adding extra search path clip X:\SD Launcher\SD nowy\Models\CLIP
Adding extra search path clip_vision X:\SD Launcher\SD nowy\Models\InvokeClipVision
Adding extra search path diffusers X:\SD Launcher\SD nowy\Models\Diffusers
Adding extra search path gligen X:\SD Launcher\SD nowy\Models\GLIGEN
Adding extra search path vae_approx X:\SD Launcher\SD nowy\Models\ApproxVAE
Adding extra search path ipadapter X:\SD Launcher\SD nowy\Models\IpAdapter
Adding extra search path ipadapter X:\SD Launcher\SD nowy\Models\InvokeIpAdapters15
Adding extra search path ipadapter X:\SD Launcher\SD nowy\Models\InvokeIpAdaptersXl
Adding extra search path prompt_expansion X:\SD Launcher\SD nowy\Models\PromptExpansion
Adding X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes to sys.path
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Loaded Efficiency nodes from X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\efficiency-nodes-comfyui
Loaded ControlNetPreprocessors nodes from X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\comfyui_controlnet_aux
Could not find AdvancedControlNet nodes
Could not find AnimateDiff nodes
Loaded IPAdapter nodes from X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
Could not find VideoHelperSuite nodes
### Loading: ComfyUI-Impact-Pack (V7.0)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.6)
### Loading: ComfyUI-Impact-Pack (V7.0)
Loaded ImpactPack nodes from X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Impact-Pack (V7.0)
[Impact Pack] Wildcards loading done.
[inference_core_nodes.controlnet_preprocessors] | INFO -> Using ckpts path: X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes\src\inference_core_nodes\controlnet_preprocessors\ckpts
[inference_core_nodes.controlnet_preprocessors] | INFO -> Using symlinks: False
[inference_core_nodes.controlnet_preprocessors] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
X:\SD Launcher\SD nowy\Packages\ComfyUI\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:249: FutureWarning: `AutoencoderTinyBlock` is deprecated and will be removed in version 0.29. Importing `AutoencoderTinyBlock` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import AutoencoderTinyBlock`, instead.
  deprecate("AutoencoderTinyBlock", "0.29", deprecation_message)
X:\SD Launcher\SD nowy\Packages\ComfyUI\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:254: FutureWarning: `UNetMidBlock2D` is deprecated and will be removed in version 0.29. Importing `UNetMidBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import UNetMidBlock2D`, instead.
  deprecate("UNetMidBlock2D", "0.29", deprecation_message)
X:\SD Launcher\SD nowy\Packages\ComfyUI\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:259: FutureWarning: `UNetMidBlock2DCrossAttn` is deprecated and will be removed in version 0.29. Importing `UNetMidBlock2DCrossAttn` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import UNetMidBlock2DCrossAttn`, instead.
  deprecate("UNetMidBlock2DCrossAttn", "0.29", deprecation_message)
X:\SD Launcher\SD nowy\Packages\ComfyUI\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:264: FutureWarning: `UNetMidBlock2DSimpleCrossAttn` is deprecated and will be removed in version 0.29. Importing `UNetMidBlock2DSimpleCrossAttn` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import UNetMidBlock2DSimpleCrossAttn`, instead.
  deprecate("UNetMidBlock2DSimpleCrossAttn", "0.29", deprecation_message)
X:\SD Launcher\SD nowy\Packages\ComfyUI\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:269: FutureWarning: `AttnDownBlock2D` is deprecated and will be removed in version 0.29. Importing `AttnDownBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import AttnDownBlock2D`, instead.
  deprecate("AttnDownBlock2D", "0.29", deprecation_message)
X:\SD Launcher\SD nowy\Packages\ComfyUI\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:274: FutureWarning: `CrossAttnDownBlock2D` is deprecated and will be removed in version 0.29. Importing `AttnDownBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import CrossAttnDownBlock2D`, instead.
  deprecate("CrossAttnDownBlock2D", "0.29", deprecation_message)
X:\SD Launcher\SD nowy\Packages\ComfyUI\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:279: FutureWarning: `DownBlock2D` is deprecated and will be removed in version 0.29. Importing `DownBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import DownBlock2D`, instead.
  deprecate("DownBlock2D", "0.29", deprecation_message)
X:\SD Launcher\SD nowy\Packages\ComfyUI\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:284: FutureWarning: `AttnDownEncoderBlock2D` is deprecated and will be removed in version 0.29. Importing `AttnDownEncoderBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import AttnDownEncoderBlock2D`, instead.
  deprecate("AttnDownEncoderBlock2D", "0.29", deprecation_message)
X:\SD Launcher\SD nowy\Packages\ComfyUI\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:289: FutureWarning: `AttnSkipDownBlock2D` is deprecated and will be removed in version 0.29. Importing `AttnSkipDownBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import AttnSkipDownBlock2D`, instead.
  deprecate("AttnSkipDownBlock2D", "0.29", deprecation_message)
X:\SD Launcher\SD nowy\Packages\ComfyUI\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:294: FutureWarning: `SkipDownBlock2D` is deprecated and will be removed in version 0.29. Importing `SkipDownBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import SkipDownBlock2D`, instead.
  deprecate("SkipDownBlock2D", "0.29", deprecation_message)
X:\SD Launcher\SD nowy\Packages\ComfyUI\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:299: FutureWarning: `ResnetDownsampleBlock2D` is deprecated and will be removed in version 0.29. Importing `ResnetDownsampleBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import ResnetDownsampleBlock2D`, instead.
  deprecate("ResnetDownsampleBlock2D", "0.29", deprecation_message)
X:\SD Launcher\SD nowy\Packages\ComfyUI\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:304: FutureWarning: `SimpleCrossAttnDownBlock2D` is deprecated and will be removed in version 0.29. Importing `SimpleCrossAttnDownBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import SimpleCrossAttnDownBlock2D`, instead.
  deprecate("SimpleCrossAttnDownBlock2D", "0.29", deprecation_message)
X:\SD Launcher\SD nowy\Packages\ComfyUI\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:309: FutureWarning: `KDownBlock2D` is deprecated and will be removed in version 0.29. Importing `KDownBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import KDownBlock2D`, instead.
  deprecate("KDownBlock2D", "0.29", deprecation_message)
X:\SD Launcher\SD nowy\Packages\ComfyUI\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:314: FutureWarning: `KCrossAttnDownBlock2D` is deprecated and will be removed in version 0.29. Importing `KCrossAttnDownBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import KCrossAttnDownBlock2D`, instead.
  deprecate("KCrossAttnDownBlock2D", "0.29", deprecation_message)
X:\SD Launcher\SD nowy\Packages\ComfyUI\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:319: FutureWarning: `AttnUpBlock2D` is deprecated and will be removed in version 0.29. Importing `AttnUpBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import AttnUpBlock2D`, instead.
  deprecate("AttnUpBlock2D", "0.29", deprecation_message)
X:\SD Launcher\SD nowy\Packages\ComfyUI\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:324: FutureWarning: `CrossAttnUpBlock2D` is deprecated and will be removed in version 0.29. Importing `CrossAttnUpBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import CrossAttnUpBlock2D`, instead.
  deprecate("CrossAttnUpBlock2D", "0.29", deprecation_message)
X:\SD Launcher\SD nowy\Packages\ComfyUI\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:329: FutureWarning: `UpBlock2D` is deprecated and will be removed in version 0.29. Importing `UpBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import UpBlock2D`, instead.
  deprecate("UpBlock2D", "0.29", deprecation_message)
X:\SD Launcher\SD nowy\Packages\ComfyUI\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:334: FutureWarning: `UpDecoderBlock2D` is deprecated and will be removed in version 0.29. Importing `UpDecoderBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import UpDecoderBlock2D`, instead.
  deprecate("UpDecoderBlock2D", "0.29", deprecation_message)
X:\SD Launcher\SD nowy\Packages\ComfyUI\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:339: FutureWarning: `AttnUpDecoderBlock2D` is deprecated and will be removed in version 0.29. Importing `AttnUpDecoderBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import AttnUpDecoderBlock2D`, instead.
  deprecate("AttnUpDecoderBlock2D", "0.29", deprecation_message)
X:\SD Launcher\SD nowy\Packages\ComfyUI\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:344: FutureWarning: `AttnSkipUpBlock2D` is deprecated and will be removed in version 0.29. Importing `AttnSkipUpBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import AttnSkipUpBlock2D`, instead.
  deprecate("AttnSkipUpBlock2D", "0.29", deprecation_message)
X:\SD Launcher\SD nowy\Packages\ComfyUI\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:349: FutureWarning: `SkipUpBlock2D` is deprecated and will be removed in version 0.29. Importing `SkipUpBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import SkipUpBlock2D`, instead.
  deprecate("SkipUpBlock2D", "0.29", deprecation_message)
X:\SD Launcher\SD nowy\Packages\ComfyUI\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:354: FutureWarning: `ResnetUpsampleBlock2D` is deprecated and will be removed in version 0.29. Importing `ResnetUpsampleBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import ResnetUpsampleBlock2D`, instead.
  deprecate("ResnetUpsampleBlock2D", "0.29", deprecation_message)
X:\SD Launcher\SD nowy\Packages\ComfyUI\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:359: FutureWarning: `SimpleCrossAttnUpBlock2D` is deprecated and will be removed in version 0.29. Importing `SimpleCrossAttnUpBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import SimpleCrossAttnUpBlock2D`, instead.
  deprecate("SimpleCrossAttnUpBlock2D", "0.29", deprecation_message)
X:\SD Launcher\SD nowy\Packages\ComfyUI\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:364: FutureWarning: `KUpBlock2D` is deprecated and will be removed in version 0.29. Importing `KUpBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import KUpBlock2D`, instead.
  deprecate("KUpBlock2D", "0.29", deprecation_message)
X:\SD Launcher\SD nowy\Packages\ComfyUI\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:369: FutureWarning: `KCrossAttnUpBlock2D` is deprecated and will be removed in version 0.29. Importing `KCrossAttnUpBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import KCrossAttnUpBlock2D`, instead.
  deprecate("KCrossAttnUpBlock2D", "0.29", deprecation_message)
X:\SD Launcher\SD nowy\Packages\ComfyUI\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:375: FutureWarning: `KAttentionBlock` is deprecated and will be removed in version 0.29. Importing `KAttentionBlock` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import KAttentionBlock`, instead.
  deprecate("KAttentionBlock", "0.29", deprecation_message)
### Loading: ComfyUI-Inspire-Pack (V0.84.1)
### Loading: ComfyUI-Manager (V2.49)
### ComfyUI Revision: 2546 [bfc214f4] | Released on '2024-08-15'
OpenPose Editor: Loaded
### Loading: PixelArtDetector
Copying PixelArtDetector JS files for Workflow loading
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
__name__ : ComfyUI_node_Lilly
__file__ : X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\ComfyUI_node_Lilly\__init__.py
os.path.basename(__file__) : __init__.py
os.path.splitext(os.path.basename(__file__))[0] : __init__
working directory :  X:\SD Launcher\SD nowy\Packages\ComfyUI
────────────────────────────────  init start  ─────────────────────────────────
__name__ : custom_nodes.ComfyUI_node_Lilly
__file__ : X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\ComfyUI_node_Lilly\__init__.py
os.path.basename(__file__) : __init__.py
os.path.splitext(os.path.basename(__file__))[0] : __init__
working directory :  X:\SD Launcher\SD nowy\Packages\ComfyUI
[13:56:07] Load ok   : CheckpointLoaderRandom                    __init__.py:83
           Load ok   : CheckpointLoaderSimpleText                __init__.py:83
[13:56:07] wildcards card_path :  X:\SD Launcher\SD             wildcards.py:36
           nowy\Packages\ComfyUI\custom_nodes\ComfyUI_node_Lill                
           y\..\..\wildcards\**\*.txt                                          
           cards file count :  0                               wildcards.py:187
           wildcards test : aest                               wildcards.py:218
           wildcards test : *test                              wildcards.py:219
           wildcards test : ?est                               wildcards.py:220
           wildcards test : test                               wildcards.py:221
           wildcards test : /test                              wildcards.py:222
           wildcards test : /0/test                            wildcards.py:223
           Load ok   : CLIPTextEncodeWildcards                   __init__.py:83
           Load ok   : LoraLoaderText                            __init__.py:83
           Load ok   : LoraLoaderTextRandom                      __init__.py:83
           Load ok   : Random_Sampler                            __init__.py:83
           Load ok   : VAELoaderDecode                           __init__.py:83
           Load ok   : VAELoaderText                             __init__.py:83
Total VRAM 12287 MB, total RAM 16328 MB
pytorch version: 2.1.2+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
           Load ok   : SimpleSampler                             __init__.py:83
           Load ok   : SaveImageSimple                           __init__.py:83
           Load ok   : TextWildcards                             __init__.py:83
─────────────────────────────────  init end  ──────────────────────────────────
Traceback (most recent call last):
  File "X:\SD Launcher\SD nowy\Packages\ComfyUI\nodes.py", line 1982, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'X:\\SD Launcher\\SD nowy\\Packages\\ComfyUI\\custom_nodes\\HandRefiner-main\\__init__.py'

Cannot import X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\HandRefiner-main module for custom nodes: [Errno 2] No such file or directory: 'X:\\SD Launcher\\SD nowy\\Packages\\ComfyUI\\custom_nodes\\HandRefiner-main\\__init__.py'
Traceback (most recent call last):
  File "X:\SD Launcher\SD nowy\Packages\ComfyUI\nodes.py", line 1982, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'X:\\SD Launcher\\SD nowy\\Packages\\ComfyUI\\custom_nodes\\MeshGraphormer-main\\__init__.py'

Cannot import X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\MeshGraphormer-main module for custom nodes: [Errno 2] No such file or directory: 'X:\\SD Launcher\\SD nowy\\Packages\\ComfyUI\\custom_nodes\\MeshGraphormer-main\\__init__.py'

[rgthree] Loaded 42 exciting nodes.
[rgthree] NOTE: Will NOT use rgthree's optimized recursive execution as ComfyUI has changed.

WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 218 nodes successfully.

	"Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work." - Steve Jobs


Import times for custom nodes:
   0.0 seconds (IMPORT FAILED): X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\MeshGraphormer-main
   0.0 seconds: X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds (IMPORT FAILED): X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\HandRefiner-main
   0.0 seconds: X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\ComfyUI-SDXL-EmptyLatentImage
   0.0 seconds: X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\sdxl-recommended-res-calc
   0.0 seconds: X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\comfyui-lama-remover
   0.0 seconds: X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\ComfyUI_experiments
   0.0 seconds: X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\ComfyUI_NestedNodeBuilder
   0.0 seconds: X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\ComfyUI-Image-Saver
   0.0 seconds: X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\ComfyUI_JPS-Nodes
   0.0 seconds: X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\ComfyUI-OpenPose-Editor
   0.0 seconds: X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.0 seconds: X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\ComfyMath
   0.0 seconds: X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\comfyui-various
   0.0 seconds: X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\ComfyUI-GGUF
   0.0 seconds: X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\ComfyUI_node_Lilly
   0.1 seconds: X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.1 seconds: X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\ComfyUI_bitsandbytes_NF4
   0.2 seconds: X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes
   0.2 seconds: X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\ComfyUI-PixelArt-Detector
   0.2 seconds: X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\comfyui_segment_anything
   0.4 seconds: X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\ComfyUI-Manager
   0.4 seconds: X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\clipseg.py
   0.8 seconds: X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\comfyui-art-venture
   1.7 seconds: X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\was-node-suite-comfyui

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[ERROR] An error occurred while retrieving information for the 'DepthAnythingPreprocessor' node.
Traceback (most recent call last):
  File "X:\SD Launcher\SD nowy\Packages\ComfyUI\server.py", line 452, in get_object_info
    out[x] = node_info(x)
  File "X:\SD Launcher\SD nowy\Packages\ComfyUI\server.py", line 425, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\depth_anything.py", line 8, in INPUT_TYPES
    ckpt_name=INPUT.COMBO(
TypeError: INPUT.COMBO() got an unexpected keyword argument 'resolution'

[ERROR] An error occurred while retrieving information for the 'ImageIntensityDetector' node.
Traceback (most recent call last):
  File "X:\SD Launcher\SD nowy\Packages\ComfyUI\server.py", line 452, in get_object_info
    out[x] = node_info(x)
  File "X:\SD Launcher\SD nowy\Packages\ComfyUI\server.py", line 426, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
AttributeError: 'NoneType' object has no attribute 'items'
```

### Browser Logs

[console-export 2.txt](https://github.com/user-attachments/files/16636799/console-export.2.txt)

### What browsers do you use to access the UI ?

Mozilla Firefox

**Comment by huchenlei** [comment]
Update your ComfyUI version to latest please.

**Comment by DonDanDojo** [comment]
> Update your ComfyUI version to latest please.

As far as I know I have the latest version. But if I'm wrong please guide me how can I update it properly
