### ISSUE TITLE
[Bug]: RangeError when loading large workflow from WebP

### ISSUE THREAD

**Issue by ArubaitoDev** [Comfy-Org/ComfyUI_frontend#774]
### Frontend Version

v1.2.47

### Expected Behavior

Workflow should load.

### Actual Behavior

Workflow does not load. Uncaught RangeError in javascript console.

### Steps to Reproduce

1. Load the default workflow and replace the Save Image Node with the builtin SaveAnimatedWEBP node (lossless: false, quality: 50, method: slowest)
2. Open the javascript console and generate 128 KiB of text, then copy and paste it into the negative prompt: `"a".repeat(2**17)`
    - In my browser the bug occurs somewhere between 64-128 KiB. It probably varies between browsers.
3. Queue Prompt
    - Output is in the attached ZIP as `bug.webp`
4. Drag and drop `bug.webp` into ComfyUI
    - **BUG**: Workflow does not load. Uncaught RangeError in javascript console.
5. Save the workflow as JSON
    - Output is in the attached ZIP as `workflow.json`
6. Drag and drop `workflow.json` into ComfyUI
    - **Correct behavior**: Workflow loads.

Attached ZIP: [bug.zip](https://github.com/user-attachments/files/16938238/bug.zip)

### Debug Logs

```powershell
None, this is a frontend issue.
```

### Browser Logs

```
Uncaught RangeError: Maximum call stack size exceeded
    at parseIFD (pnginfo.ts:53:24)
    at parseExifData (pnginfo.ts:65:19)
    at reader.onload (pnginfo.ts:112:22)
```

### What browsers do you use to access the UI ?

Brave

### Other

Spread syntax will pass one argument to `fromCharCode` for each byte of data in the workflow. If the workflow is too large this will exceed the stack size and throw an error. This can occur wherever the following pattern is used:

```javascript
String.fromCharCode(...data.slice(start, end)) // End is user controlled
```

Furthermore `TypedArray.slice` [creates a copy of the data](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/slice). This is not memory efficient.

In this case the bug happens in pngInfo.ts on [line 53](https://github.com/Comfy-Org/ComfyUI_frontend/blob/0e01bb3c07bb69d39e9bd8c484051d95ad430041/src/scripts/pnginfo.ts#L53). This seems to be the only location in the file where the bug can occur.

**Potential solution (untested)**: Instead of `slice` use [subarray](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/subarray). Then pass it to a [TextDecoder](https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder) to convert it to a string:

```javascript
const asciiDecoder = new TextDecoder("ascii");

// ...

      // Read the value(s) based on the data type
      let value
      if (type === 2) {
        // ASCII string
        value = asciiDecoder.decode(
          exifData.subarray(valueOffset, valueOffset + numValues - 1)
        )
      }
```

All mainstream browsers support these APIs.

**Comment by ArubaitoDev** [comment]
It looks like a similar solution was used to avoid this issue in the PNG metadata parser: https://github.com/Comfy-Org/ComfyUI_frontend/blob/0e01bb3c07bb69d39e9bd8c484051d95ad430041/src/scripts/metadata/png.ts#L35
