### ISSUE TITLE
[Bug]: remote doesnt work

### ISSUE THREAD

**Issue by yggdrasil75** [Comfy-Org/ComfyUI_frontend#976]
### Frontend Version

1.2.60

### Expected Behavior

remote access

### Actual Behavior

spinning circle

### Steps to Reproduce

after a recent git pull on comfyui (I havent updated it in a couple weeks, dont know which specific version it broke) remote access via nginx does not work anymore. 

### Debug Logs

```powershell
log does not proceed after the basic "ComfyUI-Manager default cache updated". no error messages to copy from it
```

### Browser Logs
```

ComfyUI Front-end version: 1.2.60
api.ts:74 
        
        
       GET https://ai.example.com/api/system_stats 404 (Not Found)
fetchApi @ api.ts:74
getSystemStats @ api.ts:456
addInitData @ logging.ts:380
ComfyLogging @ logging.ts:275
ComfyApp @ app.ts:148
(anonymous) @ app.ts:2981
VM295:1 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at ComfyApi.getSystemStats (api.ts:457:22)
    at async ComfyLogging.addInitData (logging.ts:380:25)
getSystemStats @ api.ts:457
await in getSystemStats
ComfyLogging @ logging.ts:275
ComfyApp @ app.ts:148
(anonymous) @ app.ts:2981
favicon.ico:1 
        
        
       GET https://ai.example.com/favicon.ico 404 (Not Found)
api.ts:74 
        
        
       GET https://ai.example.com/api/users 404 (Not Found)
fetchApi @ api.ts:74
getUserConfig @ api.ts:507
#setUser @ app.ts:1754
setup @ app.ts:1828
(anonymous) @ GraphCanvas.vue:111
(anonymous) @ runtime-core.esm-bundler.js:1808
callWithErrorHandling @ runtime-core.esm-bundler.js:195
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:202
hook.__weh.hook.__weh @ runtime-core.esm-bundler.js:1788
flushPostFlushCbs @ runtime-core.esm-bundler.js:379
flushJobs @ runtime-core.esm-bundler.js:415
Promise.then
queueFlush @ runtime-core.esm-bundler.js:319
queuePostFlushCb @ runtime-core.esm-bundler.js:339
queueEffectWithSuspense @ runtime-core.esm-bundler.js:1760
scheduler @ runtime-core.esm-bundler.js:6113
resetScheduling @ reactivity.esm-bundler.js:262
triggerEffects @ reactivity.esm-bundler.js:306
triggerRefValue @ reactivity.esm-bundler.js:1071
set value @ reactivity.esm-bundler.js:1118
finalizeNavigation @ vue-router.mjs:3460
(anonymous) @ vue-router.mjs:3325
Promise.then
pushWithRedirect @ vue-router.mjs:3292
push @ vue-router.mjs:3217
install @ vue-router.mjs:3659
use @ runtime-core.esm-bundler.js:2984
(anonymous) @ main.ts:27
Show 20 more frames
Show less
logging.ts:331 SyntaxError: Unexpected end of JSON input
    at ComfyApi.getUserConfig (api.ts:507:44)
    at async #setUser (app.ts:1754:24)
    at async ComfyApp.setup (app.ts:1828:5)
    at async GraphCanvas.vue:111:9
```

### What browsers do you use to access the UI ?

Brave

### Other

using legacy works fine.
my nginx config was pointing to /comfyui/ as I use the same subdomain for multiple things, but to test I pointed it to comfyui.<mysite>.com instead. neither option worked.

**Comment by huchenlei** [comment]
Duplicated https://github.com/Comfy-Org/ComfyUI_frontend/issues/941
