### ISSUE TITLE
[Bug]: Right-click menu "Card" shape option causes webpage to freeze

### ISSUE THREAD

**Issue by patrick-csliu** [Comfy-Org/ComfyUI_frontend#979]
### Frontend Version
**v1.2.47**
{
  "system": {
    "os": "nt",
    "comfyui_version": "v0.2.2",
    "python_version": "3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]",
    "pytorch_version": "2.4.1+cu124",
    "embedded_python": true,
    "argv": [
      "ComfyUI\\main.py",
      "--windows-standalone-build"
    ]
  },
}

### Expected Behavior

When selecting the "Card" option in the appearance option "Shape" from the right-click menu at the node block, the appearance of the node block should change to reflect the selected "Card" shape option correctly.

### Actual Behavior

When selecting the "Card" shape option from the right-click menu at the node block:

1. The entire webpage becomes stuck.
2. The appearance of the node block does not properly reflect the "Card" shape.
![370867202-f304e775-a5bb-4079-995c-e9f18afa0ec2](https://github.com/user-attachments/assets/93ed562e-5822-4425-b280-5685cf966a63)

### Steps to Reproduce

1. Right-click on a node block.
2. Navigate to the "Shapes" option in the right-click menu.
3. Select the "Card" shape option.
4. Observe that the webpage becomes unresponsive, and the "Card" shape does not display correctly.

### Debug Logs

```powershell
No useful information.
---------------------
FETCH DATA from: C:\Users\01pat\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
```

### Browser Logs

```
index.html:4 ComfyUI Front-end version: 1.2.47
chext_driver.js:505 Initialized driver at: Thu Sep 26 2024 04:05:58 GMT+0800 (台北標準時間)
chext_loader.js:71 Initialized chextloader at: 
api.ts:73 
        
        
       GET http://127.0.0.1:8188/api/userdata/workflows%2F.index.json 404 (Not Found)
fetchApi @ api.ts:73
getUserData @ api.ts:565
loadWorkflows @ workflows.ts:99
setup @ app.ts:1855
await in setup
(anonymous) @ GraphCanvas.vue:105
(anonymous) @ runtime-core.esm-bundler.js:1808
callWithErrorHandling @ runtime-core.esm-bundler.js:195
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:202
hook.__weh.hook.__weh @ runtime-core.esm-bundler.js:1788
flushPostFlushCbs @ runtime-core.esm-bundler.js:379
render @ runtime-core.esm-bundler.js:5805
mount @ runtime-core.esm-bundler.js:3062
app2.mount @ runtime-dom.esm-bundler.js:1530
(anonymous) @ main.ts:40
Show 8 more frames
Show less
api.ts:73 
        
        
       GET http://127.0.0.1:8188/api/userdata?recurse=true&dir=workflows&split=true net::ERR_ABORTED 404 (Not Found)
fetchApi @ api.ts:73
listUserData @ api.ts:658
loadWorkflows @ workflows.ts:108
await in loadWorkflows
setup @ app.ts:1855
await in setup
(anonymous) @ GraphCanvas.vue:105
(anonymous) @ runtime-core.esm-bundler.js:1808
callWithErrorHandling @ runtime-core.esm-bundler.js:195
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:202
hook.__weh.hook.__weh @ runtime-core.esm-bundler.js:1788
flushPostFlushCbs @ runtime-core.esm-bundler.js:379
render @ runtime-core.esm-bundler.js:5805
mount @ runtime-core.esm-bundler.js:3062
app2.mount @ runtime-dom.esm-bundler.js:1530
(anonymous) @ main.ts:40
Show 8 more frames
Show less
components-manager.js:767 Empty components: policy ignored
api.ts:73 
        
        
       GET http://127.0.0.1:8188/api/userdata/workflows%2F.index.json net::ERR_ABORTED 404 (Not Found)
fetchApi @ api.ts:73
getUserData @ api.ts:565
loadWorkflows @ workflows.ts:99
load @ workflows.ts:378
#updateActive @ workflows.ts:92
setWorkflow @ workflows.ts:173
loadGraphData @ app.ts:2229
app2.loadGraphData @ changeTracker.ts:102
app.loadGraphData @ components-manager.js:771
loadWorkflow @ app.ts:1898
setup @ app.ts:1905
await in setup
(anonymous) @ GraphCanvas.vue:105
(anonymous) @ runtime-core.esm-bundler.js:1808
callWithErrorHandling @ runtime-core.esm-bundler.js:195
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:202
hook.__weh.hook.__weh @ runtime-core.esm-bundler.js:1788
flushPostFlushCbs @ runtime-core.esm-bundler.js:379
render @ runtime-core.esm-bundler.js:5805
mount @ runtime-core.esm-bundler.js:3062
app2.mount @ runtime-dom.esm-bundler.js:1530
(anonymous) @ main.ts:40
Show 8 more frames
Show less
api.ts:73 
        
        
       GET http://127.0.0.1:8188/api/userdata?recurse=true&dir=workflows&split=true net::ERR_ABORTED 404 (Not Found)
fetchApi @ api.ts:73
listUserData @ api.ts:658
loadWorkflows @ workflows.ts:108
await in loadWorkflows
load @ workflows.ts:378
#updateActive @ workflows.ts:92
setWorkflow @ workflows.ts:173
loadGraphData @ app.ts:2229
app2.loadGraphData @ changeTracker.ts:102
app.loadGraphData @ components-manager.js:771
loadWorkflow @ app.ts:1898
setup @ app.ts:1905
await in setup
(anonymous) @ GraphCanvas.vue:105
(anonymous) @ runtime-core.esm-bundler.js:1808
callWithErrorHandling @ runtime-core.esm-bundler.js:195
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:202
hook.__weh.hook.__weh @ runtime-core.esm-bundler.js:1788
flushPostFlushCbs @ runtime-core.esm-bundler.js:379
render @ runtime-core.esm-bundler.js:5805
mount @ runtime-core.esm-bundler.js:3062
app2.mount @ runtime-dom.esm-bundler.js:1530
(anonymous) @ main.ts:40
Show 8 more frames
Show less
litegraph.es.js:8280 Uncaught ReferenceError: node is not defined
    at __LGraphCanvas.drawSelectionBounding (litegraph.es.js:8280:65)
    at __LGraphCanvas.drawNodeShape (litegraph.es.js:8231:14)
    at LGraphCanvas.drawNodeShape (app.ts:1444:37)
    at __LGraphCanvas.drawNode (litegraph.es.js:7711:12)
    at LGraphCanvas.drawNode (snapToGrid.ts:106:27)
    at LGraphCanvas.drawNode (app.ts:1577:32)
    at __LGraphCanvas.drawFrontCanvas (litegraph.es.js:7150:16)
    at __LGraphCanvas.draw (litegraph.es.js:7091:14)
    at __LGraphCanvas.renderFrame (litegraph.es.js:5594:16)
drawSelectionBounding @ litegraph.es.js:8280
drawNodeShape @ litegraph.es.js:8231
LGraphCanvas.drawNodeShape @ app.ts:1444
drawNode @ litegraph.es.js:7711
LGraphCanvas.drawNode @ snapToGrid.ts:106
LGraphCanvas.drawNode @ app.ts:1577
drawFrontCanvas @ litegraph.es.js:7150
draw @ litegraph.es.js:7091
renderFrame @ litegraph.es.js:5594
requestAnimationFrame
renderFrame @ litegraph.es.js:5598
requestAnimationFrame
renderFrame @ litegraph.es.js:5598
requestAnimationFrame
renderFrame @ litegraph.es.js:5598
requestAnimationFrame
renderFrame @ litegraph.es.js:5598
requestAnimationFrame
renderFrame @ litegraph.es.js:5598
requestAnimationFrame
renderFrame @ litegraph.es.js:5598
requestAnimationFrame
renderFrame @ litegraph.es.js:5598
requestAnimationFrame
renderFrame @ litegraph.es.js:5598
requestAnimationFrame
renderFrame @ litegraph.es.js:5598
requestAnimationFrame
renderFrame @ litegraph.es.js:5598
requestAnimationFrame
renderFrame @ litegraph.es.js:5598
requestAnimationFrame
renderFrame @ litegraph.es.js:5598
requestAnimationFrame
renderFrame @ litegraph.es.js:5598
requestAnimationFrame
renderFrame @ litegraph.es.js:5598
requestAnimationFrame
renderFrame @ litegraph.es.js:5598
requestAnimationFrame
renderFrame @ litegraph.es.js:5598
requestAnimationFrame
renderFrame @ litegraph.es.js:5598
requestAnimationFrame
renderFrame @ litegraph.es.js:5598
requestAnimationFrame
renderFrame @ litegraph.es.js:5598
requestAnimationFrame
renderFrame @ litegraph.es.js:5598
requestAnimationFrame
renderFrame @ litegraph.es.js:5598
requestAnimationFrame
renderFrame @ litegraph.es.js:5598
requestAnimationFrame
renderFrame @ litegraph.es.js:5598
requestAnimationFrame
renderFrame @ litegraph.es.js:5598
requestAnimationFrame
renderFrame @ litegraph.es.js:5598
requestAnimationFrame
renderFrame @ litegraph.es.js:5598
requestAnimationFrame
renderFrame @ litegraph.es.js:5598
requestAnimationFrame
renderFrame @ litegraph.es.js:5598
requestAnimationFrame
renderFrame @ litegraph.es.js:5598
requestAnimationFrame
renderFrame @ litegraph.es.js:5598
requestAnimationFrame
renderFrame @ litegraph.es.js:5598
requestAnimationFrame
renderFrame @ litegraph.es.js:5598
Show 38 more frames
Show less

```

### What browsers do you use to access the UI ?

Google Chrome

### Other

similar with #974

**Custom nodes**
[ComfyUI-Manager](https://github.com/ltdrdata/ComfyUI-Manager)
[UltimateSDUpscale](https://github.com/ssitu/ComfyUI_UltimateSDUpscale)
**Browser**
CHROME VERSION:
129.0.6668.71

**Comment by christian-byrne** [comment]
It was fixed in https://github.com/Comfy-Org/litegraph.js/pull/126. You will need to update ComfyUI
